apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: ${BUILD_REPOSITORY_NAME}-cloudflare-turnstile-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
spec:
  encryptedData:
    CLOUDFLARE_TURNSTILE_SECRET_KEY: AgBqjVRBQAAMmqGVc5DdOZOv4NspqQAjLaWYJTRPiTlTMWGqphqYdYKpqiFyjq59GRglAxYQr7n5zbqY5yuF/wXfPPGEUpdJzX1tL8KH37qYmkFIdIPRCt/y40I4r50FYmqwC4aXfVVcD9UvqKjB1oCwrtFXdK6WIHeZ+knd7lNc7xmyt2m4wZqi0MKZ9+oJVhm7gQMrqus2Itzb/ComEPgOy3656wrgCUigCTr2M8WpFW3xXPIEXuGUZdwbUq/Xui6LmZaslPkVoJGIN7SRgaUvGgyAdbJmW7A1iAuSvROffbHxLk3ZXh2Fl4gleGmtdKWf2pfr79UY7jMXPbjcoRXRRVtgshLk3AsHqqTBzfoX4pZAJFiszrj3eQc+lf5bzsg80xsQv4XB3UK/k3vCVjcKs0qglBn/37bgD6DZMvhjDSGAtw61y2fUDFLv9CbE1HqR0luP/uW846D74/WjAimn1CghBlxJirMdYhNoka2S+sShdUYFvxh4CClbBhCCtsTuG4VG+Qc6kl285y/jGkcTO0YxDtyKGpsppeSi+zB/QZAVsfXcQiwOxQtxmkHIOu2ixympzf2ZHlkYoW2WjYF8r23NSqV52lI6ltmcv2uhuCZL9l5iHUx5jjnEjQ4xiIJ+3b6A2C3J5ZJcyHc7eXE35Tf+stRc4KoUSvDRGcop2y6JBbpZEEVFDytH0ILwEUUpl3s9bWcPoQ7qNecr4Rb6QQ2Afo2FylicM2ahwSbj0lg2SQ==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      name: ${BUILD_REPOSITORY_NAME}-cloudflare-turnstile-secret
      namespace: ${NAMESPACE}
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
