apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: ${BUILD_REPOSITORY_NAME}-econmail-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
spec:
  encryptedData:
    ECOMAIL_API_KEY: AgCcKz1C2yvnTI9bey2qqVBMSFx8IPh0DSKfidyMrndXWGY4s36ns7uapaCB13guNJtzRHkR/oRFY37qiYfjvX01IwU9zWIk6h6LeA31D7fXThTSBXoypmB3pW653dPUqqS9Z5TOMgvv/1kZdIGRYyINbqQ5oH3GR1GVa2V0u6P7ZDc7v9mTw2jfVboTNdjG5c8cnJ/4SES/cKYBYbL+h7LLtbVLFfydgQtkO2MWQh+VRSD+1nLG1CciZStLDVLMI2NAjTxs487Lv3a6tcoXuZ8jriGnTcnU1zzE/icclgCuzE9JBV5l21xem5PVij3Xj+2WW7lUAoKI17uHFSF/yBVPNwO2di2L2npe43EqlJGSd97eLt4cnSP94kD+oYHLdaA3Vl16dMqjJnA/PQdcxrXLGpKTT3BE58GCwj4bVe4qiWXyJ1BhvFpCUzxRf38uN7ntKxPpU5pJXarrOiaz/lNhZPtnSpieZ6xQUa5b2FjcrX0HaOUovFmI10eIbi2I+RCt9yvF93sP4vG5sbJ0A1fIYtQnpi+YCCRe1cIM1ChlPd1cAGGxBDq16QdcrTA3QkInHviomBwLHs6rgg1e+f/0xVpKZUG2aCOd8GpKKp5uCBwCVNe5g3zIZZvtzrQiQIcvuWWInA3LrUR7eJnZgKuA21wfT29e19m7yhemUFydWkCMj2k/RxXP0IkYXsHE+QO1I+OzsGJKX0+4JvHtD+pp+iMDLqzkzlRmX5QuPiXS2n5qp3wtMuDwKycwxoomJju6T/sLs8tSITPusRtbeWjr
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-econmail-secret
      namespace: ${NAMESPACE}
