apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: ${BUILD_REPOSITORY_NAME}-ecomail-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
spec:
  encryptedData:
    ECOMAIL_API_KEY: AgDCl50TLK9lnrUxr52yhbwe+Q4eLAvmsDzwyeseU+sz2wJKo+PPjymvs+jMQrZoUCgEnqJ09K6ZacgYng0rIUNL39plVfaO0qTpKvfy8q99M9MN6jLTcA3T8jaRR6bmnCwuj2UOGlUc1fHLD44NU0ziLSq/5izK0G6LCti0pJbDc4DPELEtrhH8RHlJDWtRmJ5AmeGSP6sDHudd2cBBK7cDoKf4FQr3Mk3n54RLKpXYa2bkNoKVN9CJj5pyB1A3kJ1lT1SwvX5g79+TdmDs/HP4B4+s37TDrBaKEaSEJ7Lz15dKsRL/NkBkeqfdcxBhLhbhCspJa2hyp0wkQUiKZGUuMvisMet/jezX3aP/OCui+onJzjBLG9piLTzKURyqD7wckdfFs5XzOX9Lb9hc7VpnhWFnehdXLHPp8Nnov8rSPAbbXTHg6VAJ30v6F+wZN5mB1i6fj/Onz7mSNjhZ1TKLYOiYhwRNud/C2fULWoripdyeWQFjU2M3c0zioxSGEI28qoQlX61SiJVjjc9pFtxoBvwCaasGWz5vo9QlXY61HeSTRUiLHD4+/W06siRP08mgQ80iaFPwy0o84m6Aa3gUGF2GahnpAK3W9P83QaisHBO0HytIzNGak1VUVAS2FFS2T1X50OLFYT6yr9T31wx+L8fVeXuzokXQq5Xtg8CZOoFA8QCKYG7gQTRlwkMlRA9wZrVBYXuIPa7MpI+bVabysz3967ck3rraMrudnypy5domEW9RmrX3hqN6DCBhCv6N2bF1iZz0gdf0Ymc0FjiJ
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-ecomail-secret
      namespace: ${NAMESPACE}
