### Fragments

fragment AssetCategoryEntity on AssetCategory {
  documentId
  label
  slug
}

fragment AssetEntity on Asset {
  documentId
  __typename
  title
  slug
  description
  createdAt
  publishedAt
  assetCategory {
    ...AssetCategoryEntity
  }
  file {
    ...UploadFileEntity
  }
}

### Queries

query AssetCategories {
  assetCategories {
    ...AssetCategoryEntity
  }
}

query AssetBySlug($slug: String!) {
  assets(filters: { slug: { eq: $slug } }) {
    ...AssetEntity
  }
}
