query BasicDocumentBySlug($slug: String!) {
  basicDocuments(filters: { slug: { eq: $slug } }) {
    ...BasicDocumentEntity
  }
}

fragment FileCategoryEntity on FileCategory {
  documentId
  name
  slug
}

query FileCategories {
  fileCategories {
    ...FileCategoryEntity
  }
}

fragment BasicDocumentFile on UploadFile {
  documentId
  url
  name
  ext
  size
}

fragment BasicDocumentEntity on BasicDocument {
  documentId
  slug
  title
  description
  date_added
  author
  link
  file_category {
    documentId
    name
    slug
  }
  metadata {
    ...Metadata
  }
  attachment {
    ...UploadFileEntity
  }
}

fragment Metadata on BasicDocumentMetadataDynamicZone {
  __typename

  ... on ComponentMetadataFaktury {
    id
    name
    date
    attachment {
      ...UploadFileEntity
    }
  }
  ... on ComponentMetadataMetadata {
    id
    provider
    year
    grant_name
    grant_number
    amount
    description
  }
  ... on ComponentMetadataZmluvy {
    id
    date
    number
    amount
    supplier
    subject
  }
  ... on ComponentMetadataObchodnaVerejnaSutaz {
    id
    subject
    description
    number
    date_added
    amount
    attachment {
      ...UploadFileEntity
    }
  }
  ... on ComponentMetadataObjednavky {
    id
    title
    date_period
    date_added
    attachment {
      ...UploadFileEntity
    }
  }
  ... on ComponentMetadataVerejneObstaravanie {
    id
    subject
    description
    number
    date_added
    amount
    attachment {
      ...UploadFileEntity
    }
  }
}
