fragment BlogPostSections on BlogPostSectionsDynamicZone {
  __typename
  ... on ComponentSectionsFaq {
    ...FaqSection
  }
  ... on ComponentSectionsFlatText {
    ...FlatTextSection
  }
  ... on ComponentSectionsSiteUsefullness {
    ...SiteUsefulnessSection
  }
  ... on ComponentSectionsTable {
    ...TableSection
  }
  ... on ComponentSectionsAccordion {
    ...AccordionSection
  }
  ... on ComponentSectionsDivider {
    id
  }
  ... on ComponentSectionsCta {
    ...CtaSection
  }

  ... on ComponentSectionsVideo {
    ...VideoSection
  }

  ... on ComponentSectionsAssets {
    ...AssetsSection
  }

  ... on ComponentSectionsGallery {
    ...GallerySection
  }
}

fragment BlogPostEntity on BlogPost {
  __typename
  documentId
  slug
  title
  createdAt
  publishedAt
  coverMedia {
    url
    mime
    alternativeText
    width
    height
  }
  sections {
    ...BlogPostSections
  }
  localizations {
    slug
    locale
  }
  seo {
    ...Seo
  }
}

query BlogPostStaticPaths($locale: I18NLocaleCode!) {
  blogPosts(locale: $locale, pagination: { limit: -1 }) {
    documentId
    slug
    locale
  }
}

query BlogPostBySlug($slug: String!, $locale: I18NLocaleCode!) {
  blogPosts(locale: $locale, filters: { slug: { eq: $slug } }) {
    ...BlogPostEntity
  }
}

query BlogPosts(
  $locale: I18NLocaleCode!
  $limit: Int
  $start: Int
  $sort: String = "publishedAt:desc"
) {
  blogPosts_connection(
    locale: $locale
    pagination: { limit: $limit, start: $start }
    sort: [$sort]
  ) {
    nodes {
      ...BlogPostEntity
    }
    pageInfo {
      total
    }
  }
}
