fragment EventBranchPlaceEntity on Branch {
  documentId
  ...EventBranch
}

fragment BranchPlaceEntity on Branch {
  documentId
  ...Branch
}

fragment BranchCardEntity on Branch {
  __typename
  documentId
  title
  address
  slug
  latitude
  longitude
  listingImage {
    ...UploadImageEntity
  }
  subBranches {
    ...BranchPlaceEntity
  }
}

fragment BranchEntity on Branch {
  __typename
  ...BranchCardEntity
  medias {
    ...UploadImageEntity
  }
  body
  publicTransportInfo
  barrierFreeInfo
  barrierFreeState
  phone
  email
  openingHours {
    days {
      label
      time
    }
  }
  servicePages {
    __typename
    documentId
    title
  }
  locale
  localizations {
    documentId
    title
    slug
    locale
  }
  seo {
    ...Seo
  }
}

query BranchStaticPaths($locale: I18NLocaleCode!) {
  branches(locale: $locale, pagination: { limit: -1 }) {
    slug
    locale
  }
}

query BranchBySlug($slug: String!, $locale: I18NLocaleCode!) {
  branches(locale: $locale, filters: { slug: { eq: $slug } }) {
    ...BranchEntity
  }
}
