### Fragments

fragment DisclosureEntity on DisclosureEntity {
  id
  __typename
  attributes {
    slug
    title
    description
    addedAt
    type
    file {
      data {
        ...UploadFileEntity
      }
    }
    dateFrom
    dateTo
    idNumber
    amount
    contractor
    grantProvider
    grantYear
  }
}
