### Fragments

fragment DocumentCategoryEntity on DocumentCategoryEntity {
  id
  attributes {
    label
    slug
  }
}

fragment DocumentEntity on DocumentEntity {
  id
  __typename
  attributes {
    title
    slug
    addedAt
    description
    documentCategory {
      data {
        ...DocumentCategoryEntity
      }
    }
    file {
      data {
        ...UploadFileEntity
      }
    }
  }
}

### Queries

query DocumentCategories {
  documentCategories {
    data {
      ...DocumentCategoryEntity
    }
  }
}

query DocumentBySlug($slug: String!) {
  documents(filters: { slug: { eq: $slug } }) {
    data {
      ...DocumentEntity
    }
  }
}
