fragment EventCardEntity on Event {
  documentId
  __typename
  slug
  title
  description
  createdAt
  updatedAt
  publishedAt
  locale
  dateFrom
  dateTo
  price
  eventCategory {
    documentId
    ...EventCategory
  }
  branch {
    ...EventBranchPlaceEntity
  }
  eventTags {
    documentId
    ...EventTags
  }
  listingImage {
    ...UploadImageEntity
  }
  coverImage {
    ...UploadImageEntity
  }
}

fragment EventEntity on Event {
  ...EventCardEntity
  promoted
  showForm
  guests {
    id
    name
    surname
    avatar {
      ...UploadImageEntity
    }
  }
  assets {
    ...AssetsSection
  }
  gallery {
    ...UploadImageEntity
  }
  localizations {
    slug
    locale
  }
  seo {
    ...Seo
  }
}

query EventProperties($locale: I18NLocaleCode!) {
  eventCategories(locale: $locale) {
    documentId
    title
    createdAt
    updatedAt
  }
  branches(locale: $locale) {
    ...BranchPlaceEntity
  }
  eventTags(locale: $locale) {
    documentId
    title
    slug
    createdAt
    publishedAt
    updatedAt
  }
}

query EventBySlug($slug: String!, $locale: I18NLocaleCode!) {
  events(locale: $locale, filters: { slug: { eq: $slug } }) {
    ...EventEntity
  }
}

# Generating pages for all events takes to long during build time and it is not necessary for old events
query EventStaticPaths($locale: I18NLocaleCode!) {
  events(locale: $locale, pagination: { limit: 32 }, sort: "dateFrom:desc") {
    slug
    locale
  }
}
