fragment SectionLinkPageEntity on Page {
  documentId
  title
}

fragment SectionLinkBranchEntity on Branch {
  documentId
  slug
  title
}

fragment MenuSection on ComponentMenuSections {
  id
  sectionTitle
  sectionColumnSpan
  sectionPage {
    ...PageWithBaseFieldsEntity
  }
  sectionLinks(pagination: { limit: -1 }) {
    id
    sectionLinkTitle
    sectionLinkPage {
      ...SectionLinkPageEntity
    }
    sectionLinkBranch {
      ...SectionLinkBranchEntity
    }
  }
}

fragment MenuEntity on Menu {
  documentId
  menuTitle
  menuTotalColumns
  order
  menuSections {
    ...MenuSection
  }
  createdAt
  updatedAt
}

fragment ComponentFooterFooterColumn on ComponentFooterFooterColumn {
  id
  title
  footerLink {
    id
    redirectTo {
      ...PageWithBaseFieldsEntity
    }
    title
    otherSite
  }
}

fragment FooterEntity on Footer {
  documentId
  footerColumns {
    ...ComponentFooterFooterColumn
  }
  siteMapLink {
    ...PageWithBaseFieldsEntity
  }
  privacyLink {
    ...PageWithBaseFieldsEntity
  }
}

fragment GeneralEntity on General {
  eventsPage {
    __typename
    documentId
  }
  newBooksPage {
    __typename
    documentId
  }
  privacyTermsAndConditionsPage {
    __typename
    documentId
  }
  openingHoursPage {
    __typename
    documentId
  }
  noticesPage {
    __typename
    documentId
  }
}

### Queries

query General($eventsFrom: DateTime!, $locale: I18NLocaleCode!) {
  menus(locale: $locale, sort: ["order:asc"]) {
    ...MenuEntity
  }
  upcomingEvents: events(
    locale: $locale
    sort: "dateFrom:asc"
    pagination: { start: 0, limit: 4 }
    filters: { dateTo: { gte: $eventsFrom } }
  ) {
    ...EventCardEntity
  }
  footer(locale: $locale) {
    ...FooterEntity
  }
  general(locale: $locale) {
    ...GeneralEntity
  }
}
