fragment HomepageFaqSection on ComponentHomepageFaqSection {
  id
  title
  redirectTo {
    data {
      ...PageWithBaseFieldsEntity
    }
  }
  faqs(pagination: { limit: -1 }) {
    id
    question
    answer
  }
  ctas(pagination: { limit: -1 }) {
    id
    title
    ctaRedirectTo {
      data {
        ...PageWithBaseFieldsEntity
      }
    }
  }
}

fragment HomepageMapSection on ComponentSectionsMap {
  id
  title
  branches {
    branch {
      data {
        ...BranchCardEntity
      }
    }
  }
}

fragment HomepageRegistrationInfo on ComponentHomepageRegistrationInfo {
  id
  title
  description
  redirectTo {
    data {
      ...PageWithBaseFieldsEntity
    }
  }
  registrationBenefits {
    id
    benefit
  }
}

fragment HomepageNewsSection on ComponentHomepageNewsSection {
  id
  title
  redirectTo {
    data {
      ...PageWithBaseFieldsEntity
    }
  }
}

fragment HomepagePromotedContentSection on ComponentHomepagePromotedContent {
  id
  events {
    data {
      ...EventCardEntity
    }
  }
  notices {
    data {
      ...NoticeListingEntity
    }
  }
}

query HomePage($locale: I18NLocaleCode!) {
  homePage(locale: $locale) {
    data {
      attributes {
        faqSection {
          ...HomepageFaqSection
        }
        registrationInfoSection {
          ...HomepageRegistrationInfo
        }
        newsSection {
          ...HomepageNewsSection
        }
        mapSection {
          ...HomepageMapSection
        }
        promotedContent {
          ...HomepagePromotedContentSection
        }
        localizations {
          data {
            attributes {
              locale
            }
          }
        }
        seo {
          ...Seo
        }
      }
    }
  }
  promotedNews: notices(
    locale: $locale
    sort: "publishedAt:desc"
    filters: { promoted: { eq: true } }
  ) {
    data {
      ...NoticeListingEntity
    }
  }
  promotedEvents: events(
    locale: $locale
    sort: "dateFrom:asc"
    filters: { promoted: { eq: true } }
  ) {
    data {
      ...EventCardEntity
    }
  }
  ...LatestNoticesQuery
  bookTags(pagination: { limit: -1 }) {
    data {
      ...BookTagEntity
    }
  }
}
