fragment HomepageFaqSection on ComponentHomepageFaqSection {
  id
  title
  redirectTo {
    ...PageWithBaseFieldsEntity
  }
  faqs(pagination: { limit: -1 }) {
    id
    question
    answer
  }
  ctas(pagination: { limit: -1 }) {
    id
    title
    ctaRedirectTo {
      ...PageWithBaseFieldsEntity
    }
  }
}

fragment HomepageMapSection on ComponentSectionsMap {
  id
  title
  branches {
    branch {
      ...BranchCardEntity
    }
  }
}

fragment HomepageRegistrationInfo on ComponentHomepageRegistrationInfo {
  id
  title
  description
  redirectTo {
    ...PageWithBaseFieldsEntity
  }
  registrationBenefits {
    id
    benefit
  }
}

fragment HomepageNewsSection on ComponentHomepageNewsSection {
  id
  title
  redirectTo {
    ...PageWithBaseFieldsEntity
  }
}

fragment HomepagePromotedContentSection on ComponentHomepagePromotedContent {
  id
  events {
    ...EventCardEntity
  }
  notices {
    ...NoticeListingEntity
  }
}

query HomePage($locale: I18NLocaleCode!) {
  homePage(locale: $locale) {
    faqSection {
      ...HomepageFaqSection
    }
    registrationInfoSection {
      ...HomepageRegistrationInfo
    }
    newsSection {
      ...HomepageNewsSection
    }
    mapSection {
      ...HomepageMapSection
    }
    promotedContent {
      ...HomepagePromotedContentSection
    }
    localizations {
      locale
    }
    seo {
      ...Seo
    }
  }
  promotedNews: notices(
    locale: $locale
    sort: "publishedAt:desc"
    filters: { promoted: { eq: true } }
  ) {
    ...NoticeListingEntity
  }
  promotedEvents: events(
    locale: $locale
    sort: "dateFrom:asc"
    filters: { promoted: { eq: true } }
  ) {
    ...EventCardEntity
  }
  ...LatestNoticesQuery
  bookTags(pagination: { limit: -1 }) {
    ...BookTagEntity
  }
}
