fragment NoticeEntity on Notice {
  __typename
  documentId
  publishedAt
  slug
  title
  body
  listingImage {
    ...UploadImageEntity
  }
  promoted
  assets {
    ...AssetsSection
  }
  seo {
    ...Seo
  }
  localizations {
    slug
    locale
  }
}

fragment NoticeListingEntity on Notice {
  __typename
  documentId
  slug
  title
  createdAt
  publishedAt
  listingImage {
    ...UploadImageEntity
  }
}

fragment LatestNoticesQuery on Query {
  latestNotices: notices(
    locale: $locale
    pagination: { limit: 4, start: 0 }
    sort: "publishedAt:desc"
  ) {
    ...NoticeListingEntity
  }
}

### Queries

query LatestNotices($locale: I18NLocaleCode!) {
  ...LatestNoticesQuery
}

query NoticesStaticPaths($locale: I18NLocaleCode!) {
  notices(locale: $locale, pagination: { limit: -1 }) {
    documentId
    slug
    locale
  }
}

query Notices($locale: I18NLocaleCode!, $limit: Int, $start: Int) {
  notices_connection(
    locale: $locale
    pagination: { limit: $limit, start: $start }
    sort: "publishedAt:desc"
  ) {
    nodes {
      ...NoticeListingEntity
    }
    pageInfo {
      total
    }
  }
}

query NoticeBySlug($slug: String!, $locale: I18NLocaleCode!) {
  notices(locale: $locale, filters: { slug: { eq: $slug } }) {
    ...NoticeEntity
  }
}

query OpeningHoursChangeNotices($locale: I18NLocaleCode!) {
  notices(
    filters: { isCurrentChangeInOpeningHours: { eq: true } }
    sort: "publishedAt:desc"
    pagination: { limit: -1 }
    locale: $locale
  ) {
    __typename
    documentId
    slug
    locale
    title
  }
}
