fragment PageSections on PageSectionsDynamicZone {
  __typename
  ... on ComponentSectionsFaq {
    ...FaqSection
  }
  ... on ComponentSectionsFlatText {
    ...FlatTextSection
  }
  ... on ComponentSectionsSiteUsefullness {
    ...SiteUsefulnessSection
  }
  ... on ComponentSectionsForm {
    ...FormSection
  }
  ... on ComponentSectionsSubpages {
    id
    ...SubpagesSection
  }
  ... on ComponentSectionsTable {
    ...TableSection
  }
  ... on ComponentSectionsAccordion {
    ...AccordionSection
  }
  ... on ComponentSectionsDivider {
    id
  }
  ... on ComponentSectionsCta {
    ...CtaSection
  }

  ... on ComponentSectionsVideo {
    ...VideoSection
  }

  ... on ComponentSectionsAssets {
    id
    ...AssetsSection
  }

  ... on ComponentSectionsMap {
    ...MapSection
  }

  ... on ComponentSectionsRental {
    ...RentalSection
  }

  ... on ComponentSectionsGallery {
    ...GallerySection
  }

  ... on ComponentSectionsOpeningHoursSection {
    ...OpeningHoursSection
  }

  ... on ComponentSectionsChildrenListing {
    ...ChildrenListingSection
  }

  ... on ComponentSectionsCherrypickSection {
    ...CherrypickSection
  }
}

fragment PageEntity on Page {
  __typename
  documentId
  slug
  title
  createdAt
  updatedAt
  publishedAt
  listingImage {
    name
    width
    height
    url
    createdAt
    hash
    mime
    provider
    size
    alternativeText
    updatedAt
  }
  layout
  perex
  sections {
    ...PageSections
  }

  locale
  localizations {
    ...PageLocalizationEntity
  }
  seo {
    ...Seo
  }
}

fragment PageWithBaseFieldsEntity on Page {
  __typename
  documentId
  title
  slug
  newSlug
  createdAt
  updatedAt
}

fragment PageLocalizationEntity on Page {
  __typename
  documentId
  slug
  locale
}

# strapi returns just the default locale if no locale is provided
# easiest way to get all static paths is to ask for all locales sequentially
query PagesStaticPaths($locale: I18NLocaleCode) {
  pages(locale: $locale) {
    documentId
    locale
  }
}

query PageByDocumentId($documentId: ID!, $locale: I18NLocaleCode!) {
  page(documentId: $documentId, locale: $locale) {
    ...PageEntity
  }
}
