fragment AssetsSection on ComponentSectionsAssets {
  id
  title
  assets {
    ...AssetEntity
  }
  disclosures {
    ...DisclosureEntity
  }
}

fragment GallerySection on ComponentSectionsGallery {
  id
  Gallery {
    id
    Description
    Photo {
      ...UploadImageEntity
    }
  }
}

fragment RentalSection on ComponentSectionsRental {
  id
  title
  text
  branches {
    branch {
      ...BranchCardEntity
    }
    page {
      documentId
      slug
    }
  }
}

fragment MapSection on ComponentSectionsMap {
  id
  title
  branches {
    branch {
      ...BranchCardEntity
    }
  }
}

fragment VideoSection on ComponentSectionsVideo {
  id
  youtube_url
  media {
    url
  }
}

fragment CtaSection on ComponentSectionsCta {
  id
  title
  url
}

fragment AccordionSection on ComponentSectionsAccordion {
  id
  title
  flatText {
    ...FlatText
  }
  tableRows(pagination: { limit: -1 }) {
    ...TableRowWithId
  }
  forms {
    category
    type
  }
}

fragment TableSection on ComponentSectionsTable {
  id
  primaryTitle
  secondaryTitle
  rows {
    id
    label
    value
    valueAlign
  }
}

fragment SubpagesSection on ComponentSectionsSubpages {
  id
  title
  subpages {
    id
    title
    description
    url
    page {
      ...PageWithBaseFieldsEntity
    }
  }
}

fragment FormSection on ComponentSectionsForm {
  id
  type
}

fragment SiteUsefulnessSection on ComponentSectionsSiteUsefullness {
  id
  title
  thankYouMessage
}

fragment FlatTextSection on ComponentSectionsFlatText {
  id
  content
}

fragment FaqSection on ComponentSectionsFaq {
  id
  title
  questions {
    ...AccordionItem
  }
  ctaButton
  redirectTo {
    ...PageWithBaseFieldsEntity
  }
}

fragment OpeningHoursSection on ComponentSectionsOpeningHoursSection {
  id
  title
  branchList {
    documentId
    title
    openingHours {
      ...OpeningHoursDays
    }
  }
}

fragment ChildrenListingSection on ComponentSectionsChildrenListing {
  id
  depth
}

fragment CherrypickSection on ComponentSectionsCherrypickSection {
  id
  title
  pages {
    ...PageWithBaseFieldsEntity
  }
}
