resources:
  - ../../base
  - secrets/cloudflare-turnstile.secret.yml

configMapGenerator:
  - name: ${BUILD_REPOSITORY_NAME}-env
    namespace: ${NAMESPACE}
    behavior: merge
    envs:
      - .env
