apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: ${BUILD_REPOSITORY_NAME}-ecomail-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
spec:
  encryptedData:
    ECOMAIL_API_KEY: AgBQjrDGQLZJd0sv8XVQZylOYg8bzkoJ7xfObrG5fYhShkHMd6VYlS7PsDHtcadIZxRtEwD+A7MJWAA/YmNJ8MyLklMugmuXXKZyD85mDG3rzy3nVrfFMtlGbZLZdEFBIj9YPLBD8ARdoh0CDjdPZ5P2feQatgTL0uzvuj/MQo+eyNVgDPp8bTuasaRDtnpLBAVhck1zuMd3LV6nW/W34X4glK7NSxGlwcuPHon00XtvFmo62KdOqpVhrApjeUw9FsZfyLArtCaGiJ1CJ/adVrgE7Qr+cvDVR1J7tQCjAp04LiyGsHQjnTZ036jS1SiOvY2kiapVNn+XX3nruQlqVLZcSGuEKv82FzdC1panqj16z4ieOETjhBTyn/gXQ5qw9jSe+pDuUJjFXB/MI11Exde7xXkvs0PeqzlJIO4/nQXwzbCSIShwBrLpIqIsLg+BzWKj6yfClN04SY7FZtQIRpXZSTU/O1OzyIIC7jNm1zZdigNPWnlrbIpEANbwq6wXsL958d8pVruRERh6EGYZPBybPGtYcMqu/FsO1UwZFnZrG7AhCXYwAfG9l0OYfEU4VSznP//vd+HkRa3Qr6wY9KKPN6apxiXlBQWwnpcx0vf19YgJchrJqPIRWSgGkyHUJH4OSgnqbChQMBaC0UMqOqUr3xV/OprJN7bvMSaAnfxRSxm/W68Nt1v8dlrCnnrrEcgz7HHoSNdMfhKS22HIzwG+bn6m+xYOW+59p1VDgz0fS3bHkBeVdTA9sm1BV6JWH2zyXf7TgQn0eWkcMTryYVE9
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-ecomail-secret
      namespace: ${NAMESPACE}
