import type { NextApiRequest, NextApiResponse } from 'next'

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  // Check for tmp secret to confirm this is a valid request
  if (req.query.secret !== 'Zg66syD2Jxii6fZr') {
    return res.status(401).json({ message: 'Invalid tokenn' })
  }

  try {
    await res.unstable_revalidate('/sluzby')
    console.log('Ping /sluzby')
    await res.unstable_revalidate('/sluzby')
    console.log('Ping /sluzby/citanie')
    await res.unstable_revalidate('/sluzby/citanie')
    console.log('Ping /sluzby/citanie/ako-sa-prihlasit-do-kniznice')
    await res.unstable_revalidate('/sluzby/citanie/ako-sa-prihlasit-do-kniznice')
    // console.log('Ping /sluzby/citanie/online-katalog')
    // await res.unstable_revalidate('/sluzby/citanie/online-katalog')
    // console.log('Ping /sluzby/citanie/e-knihy-a-e-casopisy')
    // await res.unstable_revalidate('/sluzby/citanie/e-knihy-a-e-casopisy')
    // console.log('Ping /sluzby/citanie/e-knihy-a-e-casopisy/palmknihy')
    // await res.unstable_revalidate('/sluzby/citanie/e-knihy-a-e-casopisy/palmknihy')
    // console.log('Ping /sluzby/citanie/e-knihy-a-e-casopisy/pressreader')
    // await res.unstable_revalidate('/sluzby/citanie/e-knihy-a-e-casopisy/pressreader')
    // console.log('Ping /sluzby/citanie/e-knihy-a-e-casopisy/ebscoebookpubliclibrarycollection')
    // await res.unstable_revalidate(
    //   '/sluzby/citanie/e-knihy-a-e-casopisy/ebscoebookpubliclibrarycollection'
    // )
    // console.log('Ping /sluzby/citanie/e-knihy-a-e-casopisy/kubo')
    // await res.unstable_revalidate('/sluzby/citanie/e-knihy-a-e-casopisy/kubo')
    // console.log('Ping /sluzby/citanie/prezencne-zdroje')
    // await res.unstable_revalidate('/sluzby/citanie/prezencne-zdroje')
    // console.log('Ping /sluzby/citanie/bibliografia-a-resers')
    // await res.unstable_revalidate('/sluzby/citanie/bibliografia-a-resers')
    // console.log('Ping /sluzby/citanie/medzikniznicna-vypozicna-sluzba')
    // await res.unstable_revalidate('/sluzby/citanie/medzikniznicna-vypozicna-sluzba')
    // console.log('Ping /sluzby/citanie/objednavka-a-rezervacia-knih')
    // await res.unstable_revalidate('/sluzby/citanie/objednavka-a-rezervacia-knih')
    // console.log('Ping /sluzby/citanie/cyklodonaska')
    // await res.unstable_revalidate('/sluzby/citanie/cyklodonaska')
    // console.log('Ping /sluzby/citanie/knizne-boxy')
    // await res.unstable_revalidate('/sluzby/citanie/knizne-boxy')
    // console.log('Ping /sluzby/citanie/knizne-novinky')
    // await res.unstable_revalidate('/sluzby/citanie/knizne-novinky')
    // console.log('Ping /sluzby/citanie/aka-kniha-v-kniznici-chyba')
    // await res.unstable_revalidate('/sluzby/citanie/aka-kniha-v-kniznici-chyba')
    // console.log('Ping /sluzby/nastroje')
    // await res.unstable_revalidate('/sluzby/nastroje')
    // console.log('Ping /sluzby/nastroje/pristup-na-internet')
    // await res.unstable_revalidate('/sluzby/nastroje/pristup-na-internet')
    // console.log('Ping /sluzby/nastroje/tlaciaren')
    // await res.unstable_revalidate('/sluzby/nastroje/tlaciaren')
    // console.log('Ping /sluzby/nastroje/kniharska-dielna')
    // await res.unstable_revalidate('/sluzby/nastroje/kniharska-dielna')
    // console.log('Ping /sluzby/nastroje/pomocky-na-citanie')
    // await res.unstable_revalidate('/sluzby/nastroje/pomocky-na-citanie')
    // console.log('Ping /sluzby/nastroje/tablety-a-citacky')
    // await res.unstable_revalidate('/sluzby/nastroje/tablety-a-citacky')
    // console.log('Ping /sluzby/nastroje/darcekova-poukazka')
    // await res.unstable_revalidate('/sluzby/nastroje/darcekova-poukazka')
    // console.log('Ping /sluzby/nastroje/hra-na-hudobne-nastroje')
    // await res.unstable_revalidate('/sluzby/nastroje/hra-na-hudobne-nastroje')
    // console.log('Ping /sluzby/nastroje/divadelna-technika')
    // await res.unstable_revalidate('/sluzby/nastroje/divadelna-technika')
    // console.log('Ping /sluzby/vzdelavanie')
    // await res.unstable_revalidate('/sluzby/vzdelavanie')
    // console.log('Ping /sluzby/vzdelavanie/clanky')
    // await res.unstable_revalidate('/sluzby/vzdelavanie/clanky')
    // console.log('Ping /sluzby/dalsie-informacie')
    // await res.unstable_revalidate('/sluzby/dalsie-informacie')
    // console.log('Ping /sluzby/dalsie-informacie/casto-kladene-otazky')
    // await res.unstable_revalidate('/sluzby/dalsie-informacie/casto-kladene-otazky')
    // console.log('Ping /sluzby/dalsie-informacie/napiste-nam')
    // await res.unstable_revalidate('/sluzby/dalsie-informacie/napiste-nam')
    // console.log('Ping /zazite')
    // await res.unstable_revalidate('/zazite')
    // console.log('Ping /zazite/podujatia')
    // await res.unstable_revalidate('/zazite/podujatia')
    // console.log('Ping /zazite/aktuality')
    // await res.unstable_revalidate('/zazite/aktuality')
    // console.log('Ping /zazite/pre-skoly')
    // await res.unstable_revalidate('/zazite/pre-skoly')
    // console.log('Ping /zazite/studujte-v-kniznici')
    // await res.unstable_revalidate('/zazite/studujte-v-kniznici')
    // console.log('Ping /zazite/prenajmite-si-priestor')
    // await res.unstable_revalidate('/zazite/prenajmite-si-priestor')
    // console.log('Ping /zazite/prenajmite-si-priestor/galeria-artoteka')
    // await res.unstable_revalidate('/zazite/prenajmite-si-priestor/galeria-artoteka')
    // console.log('Ping /zazite/prenajmite-si-priestor/pod-kniznicou')
    // await res.unstable_revalidate('/zazite/prenajmite-si-priestor/pod-kniznicou')
    // console.log('Ping /zazite/prenajmite-si-priestor/hudobne-studio')
    // await res.unstable_revalidate('/zazite/prenajmite-si-priestor/hudobne-studio')
    // console.log('Ping /navstivte')
    // await res.unstable_revalidate('/navstivte')
    // console.log('Ping /navstivte/nase-lokality')
    // await res.unstable_revalidate('/navstivte/nase-lokality')
    // console.log('Ping /navstivte/klariska')
    // await res.unstable_revalidate('/navstivte/klariska')
    // console.log('Ping /navstivte/kapucinska')
    // await res.unstable_revalidate('/navstivte/kapucinska')
    // console.log('Ping /navstivte/letna-citaren-klariska')
    // await res.unstable_revalidate('/navstivte/letna-citaren-klariska')
    // console.log('Ping /navstivte/laurinska')
    // await res.unstable_revalidate('/navstivte/laurinska')
    // console.log('Ping /navstivte/letna-citaren-u-cerveneho-raka')
    // await res.unstable_revalidate('/navstivte/letna-citaren-u-cerveneho-raka')
    // console.log('Ping /navstivte/ostatne/galeria-artoteka')
    // await res.unstable_revalidate('/navstivte/ostatne/galeria-artoteka')
    // console.log('Ping /navstivte/ostatne')
    // await res.unstable_revalidate('/navstivte/ostatne')
    // console.log('Ping /navstivte/ostatne/otvaracie-hodiny')
    // await res.unstable_revalidate('/navstivte/ostatne/otvaracie-hodiny')
    // console.log('Ping /navstivte/ostatne/kde-nas-najdete')
    // await res.unstable_revalidate('/navstivte/ostatne/kde-nas-najdete')
    // console.log('Ping /o-nas')
    // await res.unstable_revalidate('/o-nas')
    // console.log('Ping /o-nas/kontakty')
    // await res.unstable_revalidate('/o-nas/kontakty')
    // console.log('Ping /o-nas/z-historie')
    // await res.unstable_revalidate('/o-nas/z-historie')
    // console.log('Ping /o-nas/vizia')
    // await res.unstable_revalidate('/o-nas/vizia')
    // console.log('Ping /o-nas/organizacna-struktura')
    // await res.unstable_revalidate('/o-nas/organizacna-struktura')
    // console.log('Ping /o-nas/dokumenty-a-zverejnovanie-informacii')
    // await res.unstable_revalidate('/o-nas/dokumenty-a-zverejnovanie-informacii')
    // console.log('Ping /o-nas/verejne-kniznice-a-metodika')
    // await res.unstable_revalidate('/o-nas/verejne-kniznice-a-metodika')
    // console.log('Ping /o-nas/partneri-a-spoluprace')
    // await res.unstable_revalidate('/o-nas/partneri-a-spoluprace')
    // console.log('Ping /o-nas/ochrana-osobnych-udajov')
    // await res.unstable_revalidate('/o-nas/ochrana-osobnych-udajov')
    // console.log('Ping /en/services')
    // await res.unstable_revalidate('/en/services')
    // console.log('Ping /en/services//reading')
    // await res.unstable_revalidate('/en/services//reading')
    // console.log('Ping /en/services/reading/how-to-register-at-the-library')
    // await res.unstable_revalidate('/en/services/reading/how-to-register-at-the-library')
    // console.log('Ping /en/services/reading/online-catalog')
    // await res.unstable_revalidate('/en/services/reading/online-catalog')
    // console.log('Ping /en/services/reading/e-books-and-e-maganizes')
    // await res.unstable_revalidate('/en/services/reading/e-books-and-e-maganizes')
    // console.log('Ping /en/services/reading/e-books-and-e-maganizes/palmknihy')
    // await res.unstable_revalidate('/en/services/reading/e-books-and-e-maganizes/palmknihy')
    // console.log('Ping /en/services/reading/e-books-and-e-maganizes/pressreader')
    // await res.unstable_revalidate('/en/services/reading/e-books-and-e-maganizes/pressreader')
    // console.log(
    //   'Ping /en/services/reading/e-books-and-e-maganizes/ebsco-ebook-public-library-collection'
    // )
    // await res.unstable_revalidate(
    //   '/en/services/reading/e-books-and-e-maganizes/ebsco-ebook-public-library-collection'
    // )
    // console.log('Ping /en/services/reading/e-books-and-e-maganizes/kubo')
    // await res.unstable_revalidate('/en/services/reading/e-books-and-e-maganizes/kubo')
    // console.log('Ping /en/services/reading/on-site-resources')
    // await res.unstable_revalidate('/en/services/reading/on-site-resources')
    // console.log('Ping /en/services/reading/bibliography-and-library-research')
    // await res.unstable_revalidate('/en/services/reading/bibliography-and-library-research')
    // console.log('Ping /en/services/reading/interlibrary-loan-service')
    // await res.unstable_revalidate('/en/services/reading/interlibrary-loan-service')
    // console.log('Ping /en/services/reading/orders-and-reservations')
    // await res.unstable_revalidate('/en/services/reading/orders-and-reservations')
    // console.log('Ping /en/services/reading/bicycle-delivery')
    // await res.unstable_revalidate('/en/services/reading/bicycle-delivery')
    // console.log('Ping /en/services/reading/book-boxes')
    // await res.unstable_revalidate('/en/services/reading/book-boxes')
    // console.log('Ping /en/services/reading/new-additions')
    // await res.unstable_revalidate('/en/services/reading/new-additions')
    // console.log('Ping /en/services/reading/a-book-that-is-missing-in-the-library')
    // await res.unstable_revalidate('/en/services/reading/a-book-that-is-missing-in-the-library')
    // console.log('Ping /en/services/tools')
    // await res.unstable_revalidate('/en/services/tools')
    // console.log('Ping /en/services/tools/internet-access')
    // await res.unstable_revalidate('/en/services/tools/internet-access')
    // console.log('Ping /en/services/tools/printing')
    // await res.unstable_revalidate('/en/services/tools/printing')
    // console.log('Ping /en/services/tools/bookbinding-workshop')
    // await res.unstable_revalidate('/en/services/tools/bookbinding-workshop')
    // console.log('Ping /en/services/tools/reading-aids')
    // await res.unstable_revalidate('/en/services/tools/reading-aids')
    // console.log('Ping /en/services/tools/tablets-and-readers')
    // await res.unstable_revalidate('/en/services/tools/tablets-and-readers')
    // console.log('Ping /en/services/tools/gift-certificate')
    // await res.unstable_revalidate('/en/services/tools/gift-certificate')
    // console.log('Ping /en/services/tools/musical-instruments')
    // await res.unstable_revalidate('/en/services/tools/musical-instruments')
    // console.log('Ping /en/services/tools/theater-technology')
    // await res.unstable_revalidate('/en/services/tools/theater-technology')
    // console.log('Ping /en/services/education')
    // await res.unstable_revalidate('/en/services/education')
    // console.log('Ping /en/services/education/articles')
    // await res.unstable_revalidate('/en/services/education/articles')
    // console.log('Ping /en/services/other-information')
    // await res.unstable_revalidate('/en/services/other-information')
    // console.log('Ping /en/services/other-information/frequently-asked-questions')
    // await res.unstable_revalidate('/en/services/other-information/frequently-asked-questions')
    // console.log('Ping /en/services/other-information/contact-us')
    // await res.unstable_revalidate('/en/services/other-information/contact-us')
    // console.log('Ping /en/experience')
    // await res.unstable_revalidate('/en/experience')
    // console.log('Ping /en/experience/events')
    // await res.unstable_revalidate('/en/experience/events')
    // console.log('Ping /en/experience/news')
    // await res.unstable_revalidate('/en/experience/news')
    // console.log('Ping /en/experience/for-schools')
    // await res.unstable_revalidate('/en/experience/for-schools')
    // console.log('Ping /en/experience/study-in-the-library')
    // await res.unstable_revalidate('/en/experience/study-in-the-library')
    // console.log('Ping /en/experience/rent-a-space')
    // await res.unstable_revalidate('/en/experience/rent-a-space')
    // console.log('Ping /en/experience/rent-a-space/artoteka-gallery')
    // await res.unstable_revalidate('/en/experience/rent-a-space/artoteka-gallery')
    // console.log('Ping /en/experience/rent-a-space/under-the-library')
    // await res.unstable_revalidate('/en/experience/rent-a-space/under-the-library')
    // console.log('Ping /en/experience/rent-a-space/music-studio')
    // await res.unstable_revalidate('/en/experience/rent-a-space/music-studio')
    // console.log('Ping /en/visit')
    // await res.unstable_revalidate('/en/visit')
    // console.log('Ping /en/visit/our-locations')
    // await res.unstable_revalidate('/en/visit/our-locations')
    // console.log('Ping /en/visit/klariska')
    // await res.unstable_revalidate('/en/visit/klariska')
    // console.log('Ping /en/visit/kapucinska')
    // await res.unstable_revalidate('/en/visit/kapucinska')
    // console.log('Ping /en/visit/summer-reading-room-klariska')
    // await res.unstable_revalidate('/en/visit/summer-reading-room-klariska')
    // console.log('Ping /en/visit/laurinska')
    // await res.unstable_revalidate('/en/visit/laurinska')
    // console.log('Ping /en/visit/summer-reading-room-u-cerveneho-raka')
    // await res.unstable_revalidate('/en/visit/summer-reading-room-u-cerveneho-raka')
    // console.log('Ping /en/visit/others')
    // await res.unstable_revalidate('/en/visit/others')
    // console.log('Ping /en/visit/other/artoteka-gallery')
    // await res.unstable_revalidate('/en/visit/other/artoteka-gallery')
    // console.log('Ping /en/visit/other/opening-hours')
    // await res.unstable_revalidate('/en/visit/other/opening-hours')
    // console.log('Ping /en/visit/other/find-us')
    // await res.unstable_revalidate('/en/visit/other/find-us')
    // console.log('Ping /en/about-us')
    // await res.unstable_revalidate('/en/about-us')
    // console.log('Ping /en/about-us/contacts')
    // await res.unstable_revalidate('/en/about-us/contacts')
    // console.log('Ping /en/about-us/history')
    // await res.unstable_revalidate('/en/about-us/history')
    // console.log('Ping /en/about-us/vision')
    // await res.unstable_revalidate('/en/about-us/vision')
    // console.log('Ping /en/about-us/organizational-structure')
    // await res.unstable_revalidate('/en/about-us/organizational-structure')
    // console.log('Ping /en/about-us/documents-and-public-disclosure-of-information')
    // await res.unstable_revalidate('/en/about-us/documents-and-public-disclosure-of-information')
    // console.log('Ping /en/about-us/public-libraries-and-methodology')
    // await res.unstable_revalidate('/en/about-us/public-libraries-and-methodology')
    // console.log('Ping /en/about-us/partners-and-cooperation')
    // await res.unstable_revalidate('/en/about-us/partners-and-cooperation')
    // console.log('Ping /en/about-us/privacy-terms-and-conditions')
    // await res.unstable_revalidate('/en/about-us/privacy-terms-and-conditions')

    // Check model
    // const payload = req.body
    // if (payload?.model === 'blog-post') {
    //   const blogPostUrl = `/blog/${payload?.entry?.slug}`
    //   await res.unstable_revalidate(blogPostUrl)
    // }

    // if (payload?.model === 'page') {
    //   const pageUrl = `/${payload?.entry?.slug}`
    //   await res.unstable_revalidate(pageUrl)
    // }

    return res.json({ revalidated: true })
  } catch (err) {
    console.log('Error while revalidating ==>', err)
    return res.status(500).send('Error revalidating')
  }
}
