apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
  name: ${BUILD_REPOSITORY_NAME}-app-keys-secret
  namespace: "${NAMESPACE}"
spec:
  encryptedData:
    APP_KEYS: AgBYfuTO/0QPcXWNKl83gCAaUeuddC/xPRSJ349E6NJoW1pFFeytUlJH6hFLPn3mBGiz/vOddiRZ52NbT3rp4pzbUbEIlfQVSTkSsi1y0GJIVQzPpoet0p2A9FrokvpMcJ6VvXd1BAmVV+42/bWtPfnowjSCVCF6G7UsCnHlXYnAUJ9mv0qs+AvNoFYfNmx7yIsvp/DcGEDhl3o/1n6izVh4rjXXWrOiZDXekELd+4JHPX/cNVFuh/jwwaNkVuYTjZLsIMNj/fnEjaTJKANv7sVJCpbP14BdbOvFRIkn8Ny/9JEA7sqv35EWLP1xDHLzd4wt9nRKclu7m33wYi/3Wg78ng7ZpeOBTY02Z/cy4Pyvoz608KzG1SVwUHHf5vwVTKP0qON0bMMR5D+ZThCnlKuSXHB9cr7i6Shji7EeFYxIKAN/cAgRKldTj6sEsijHkkdmefuelYLb//EQApV3Jm3eRNeURm2uMiuoaiOtlwlahuFWVKQ5+ieEBFmmFBMvCKzGaNX3wurR8JvKRHr760o9bjIoPCMcWxDunAT464ye2DSn137krhs/TBh8OMrqHtKg2IyE34ERCsSU+WBGfuFZe/02Cl3XUAHU+eVZBIAJk1boEkC4G2shsLmHLPgXa8EasYkxS99ANBZJ6gxdekpB/TmngqIwlmuei9a47/b0pc/+vW/gXRfTfRODxnHaEQK64dkRoAC6c+IYoQHH1Rfye08skKGY4DRJbuoabiCrJaZ/FEnmfzaUsR2aBU2PsKlh+YZGXeny9V5FLn/7EN5jLmpTItN3iklF1ngb5ArFJM6fqaxjy/cCb1a8YBRM7HJULU4a6bKIOe3XdImNWlfo0WfgZWbt1cer/d72lqdq1Fdra2J/Qj2XSRM66YDzI4CDQF9Fo5qw/qBEFoBg/mqwi2/9wlKQ54MbX/Bxr1tcPw2yMaFvcpvt9TB71XbKo37WKJH8POzg950PuHW8CuatVJC/vb9JjTf4OiV8FooTvRuNap7V1xannDDDE7bSXJbX5J6/
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-app-keys-secret
      namespace: "${NAMESPACE}"
