apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
  name: ${BUILD_REPOSITORY_NAME}-config-strapi-secret
  namespace: "${NAMESPACE}"
spec:
  encryptedData:
    ADMIN_JWT_SECRET: AgCf9RGsHWX9xOgPp6cO+rzZBPyDiIe1O+FYBwfTKl51o+16nxx4EFuAz+mvlGbJ3IN7cpGLsGOriY+bCpUDvBvA4X14tGFpuWCRGBh/5gJyTw+DUBo6Owi1CYNC92d7hJ8b/M4EWg/4rMWgsbI0I9RviM5ier5OGM6w4JRp5xIFJyNPAgDMKDEz6AhEciJAaRYutdOubMCin9PmOhrFmyaukhVQ1vUT315nSqmbo0XHKZithk3SOAw1A66Ebze3v9S2PzWEHZuy4NeXvQqg61ihu9BAPBjH5M0BIMDa3v2aSIJy8Z/+RiRbgRzx631OQSifu2gYoMj6/uA+UArfG35XquS5oMUl4CgRQZ6AmVS1vif9hzQlPHkE2Wx7cDSSmlFbNB/ekhdRcLkRouLVI/9ZaPdKEYBf3YY1ddHFT4+ZwKC1p/spk4vs4wypRunVKJvUeyOHh0LvMRKYn8Q7RKmPkGeN2rm4V9CTUa1h3npNl5mhH+fKsmDNamL9g6oc7MhwhGJ5j/pNNKgOrHu7tXmyHmRADsuVY6DidxTBz3BubaJ2VFs5XcPS3NozIA+MYj4v77RKTMVHAVBR/rke538jZ+rit2HWPpjh0iRat0Gb9h77y6UaJ5Izn4fr49rhsQAcQ2Nqtd8wvDnbQtYRpAtmnnmXrgVokcr15qn4j/KjlY5tNw2K2OWfP9TJC1/0vQKsBBnkeA1h+veyE+GDMRDHA+E8/7JBbJKadi8p
    API_TOKEN_SALT: AgB6qiMuRbdwLecmcr1F4yB8Z8nXSWllkmY/M2F817RuSEEXQyxmVErH48RirG65z+JVavcWR/B7LzNhrxHXSUkFqUBW+RrecLoZsU3HTKKFnB0REN56e9i69Evo7Ex4NbNVVhTZdESn8LRZSaLh8wylRdwYwsfd8HfpXoH6lJ8yMAZbOYTzUUQCFfXPN3WR0DK3OR5fUFROs4x3MAQwVVi7s0ZuC6aNMIaEQbV8R9RRcZZdaICyE5BjQEJiZ/u0GXVJJmMEmIqaFwIPyTNKaN3+AE5lVker0MxKQdUTQy/uazv9b6/9i9tBNxy121Ayqr/BpOh4PJWgJU3wwQq4mBoH+Z/+1u+zavYlV1h6Xma0FH1PGa0izc6yptUexlsFAnkT8cn5b5y0JO2WL9+RdGyjo+WnFT4BPAsQzUufptqE2Exox87mRrK7P32WYgb4enGbPRFlhWyZiFm7IZQL8UIUFpXbTxX7sW7kcIjuZrxLggLaXAkkf8EuxCyWnbQ4S9/VjU6F2sMwldlXOF7v5P/uGnHEzWLixaXeq/nOUre22Q5mQQxUqZw/wWRPEX5mni0EyLRTEnCgZrueDQRxAUyAP49+k+RoosHL5+8osmut1AFWY8CktDR9QfJ6I9io3E7QAUuooOAEUf2y5+XH11v5DRKSn5Y4EXSa5ke6XuC1i9F9uqcnyTacJyTFncdwai0QDYSCo7Q9/SfLGLwldhfXeXK3belS1490LqKzTw==
    JWT_SECRET: AgDOTzpxFXWFFLWDH4g2NcugIcCMLQvo5HRjP0nKVeM32NDk+R2EfzEoKAEilb0nwk9wiZv50x2PBr/Bsx1lwr93OgLwV17uxCDm3n6cbcLOKZVmUMKw4YJS/VgHP3pts0CjIALaqg5NNX4DuDiYSzUEVsZcPGKmwZGSzKOFcOXHbLNbVKAU8eUrCbCCtJvHXHethbchueVwxT+qS/Io7u5nG0NaziApLAChoPX5j3TCE3NS0qrjSx/ByOJCMeSs2S4BDEtQ5iyRL2mlt1LmwbKmibWPbGI4c2+Md/bL0R/ENzhf/J6lDQYW64DHS+9djKj2+9ZC7dknOqa8kjyylWHkf87dkt6vmcM7q0UloF1fuiBchV6YDkCBVQEgAoBVPsd2OgJgnIEzknmiKUabzm6oYm8P6kuLtP0f6w4GjfkQG5OgG8t6yQ0ruojwuvI/rTPmKmJKHfb6OFw1nMkv5XYIhNhZu/tByIQLqaqewFqXb9GSiRB69h1hjFFKiAhbGagk/1Gtv4cd1F16xTF0+2pBxm+O4fQg+d8G5NrutHOZcqoaUqbl7zitpdENDfHiMba5EBTTYW3pWv6vnJyILRoNqBJ6KMQPlYrCxijfo6TPD4d7K8Uqo4UvvtosPg8aOEv9H5JCuWtdQ+h2tQCyfNp00xucoKTFvAtAnKhI0GEgX03zK3adNX2WpKp18hRvgV1e6942kS56bT7R5HByV4YEh3Sy+7OcPsW/LqU=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-config-strapi-secret
      namespace: "${NAMESPACE}"
