apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
  name: ${BUILD_REPOSITORY_NAME}-database-secret
  namespace: "${NAMESPACE}"
spec:
  encryptedData:
    DATABASE_PASSWORD: AgBSsafqpZ4brTxb72LZA1RoGEeRxTuMsXDbtn1GIp7ZYwiBel2KYGajKPWYU4EugQZ2TZAMKIFGzzvJHJWCyPdyoHk8X7b0hL/7UPHUa54IneKc0L4PaFe7SNmAumxTAK5lcnPlG21Xdakgi5S2H1F/i89QPHkpcMndaCg/ax8E58CJN9VWLfDI9rbhgEqcdUVKnCQMJnfFwV/ECBH7AN33LqnHVK89PpaY/Aw89o/rYWMbFHt0RQuc4/ufxnioU6j7ZsBkuKRgIuH6rqyxmRHYi4FfFgG6VYs/3UbMHMbK8wf1J03bJKmhNEiQ8HYCpzYCODPVoRHa4B/aF8CSBNwyK3vI9/WRf7cqHqZGSfDVDb4oQO43q4XV+2S/+q6Q33TVUfdzXHsz/4yWvSnYnr6+BLoWbKSDJizhTaK0dSq5mPsZl/CS9Zwh9jVkD2FjXhgzrvF+qt/h0nwm/3zgrXEkdy29sGkowGUUzIinISAkBRP132qh5QWr3pymC7Nyd0xPBIpmvwC/y/YlSwmFrmVx1hXkbrpucICZLNVlhAsrej3cF6nrzBLUclVce58kTStspvb0Xfcj9z3hp+ni7ETjRnvNMzJvLO5xVy5YfU5cCPXvcrYQfhD2TjWd8hLIEd4z+LLNbouexlAepQSJD25+1rV6ZhzOT6t/AtxU8HHqNozE3FuXjkPxOD10N7MyQ1Jxuh9TL1Bcf2KvOjQG52TX+0bVFct2hiRSRTVKdpy078hYIuJxXVOp02s=
    POSTGRES_PASSWORD: AgCQSiwRVhh83yXTCPxTZbskez8GExY9xWiXweyadphZZ7p7ylS2YL2DXtaOgSHJH0F9+DttUVAIcwGcMJJAx26pJLikAxLezTx5Ib6+UlFdiRNZCn+uGz+RFLe4TlID8czaVTdpgDtA5hJvusltUjJ66TjdZLnaNSoBKdc1soQ7D42nqr3L76WPK22G1dPsAMqY6cNxWO69Z5wT9vDTz5iuZeDYc2DXjR+wHqMB0ZV3KEc05aa4Wgyyu5yEkFHK3z0aPNaVkfVRxITdCWSgrpHsSNQzHLXLa2UrV8bHfvjncRm3vW3jlIeeaf0Kyz1XOzoKgEzanYNHTCx60dmJ3+48kNwLAvw+S8d12QgC5NtPFhDCVSylRhnElk7IrTQ04vFNOlB2GHw1vDJSDsLd15CO16yyfkf2byjcGCBpwef7bhy6reXRDqrWhdM2gZCWu+xOhspP+4j/DkcU2b7wR0JYPpY4tWYGW/y3XNHSrvlB4ylGtMNH7on0JRsFuf0MWaTAbUfVhk4oS2h9SghhzeAbFUhUMsHxvGcmKgaWdfRIn0mGLBj/tKN7gd830TPRW3n7Uh/o3Y+cYfr562S3ZgwcT0Fga2inl7goN7g86+us16bm22l5tLRM+iKUkufeJ5sPRVoJwuzT/zKNck0b11WNx3+RosNMIiKZtKzSvFNyrHmqMthHw0B9qu8E2FLuxTtTVzUAFmfKbyTND5xIrq0sAZVsU4c1wuYChcm0/uw7Uy+qhuxhOxfFI/U=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-database-secret
      namespace: "${NAMESPACE}"
