apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: ${BUILD_REPOSITORY_NAME}-revalidate-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
spec:
  encryptedData:
    REVALIDATE_SECRET_TOKEN: AgCuJ3JmxzzSeX2nDsvGH+PSWVO+70JYU0W1H9Z/4kfoU4GDsqsHXvNyEUTrQBX24bprF78rE07vvF5x2xtR4U2oubW3TrsUNVFyup2dd7PGXIhH27y0MKtWaPV0tisCnYtyuzSw4YyN0WZvYqUip9b8k6+UbemOMtYtG7S0KQUNmFWYynfM/3jezYi+Dxg3eCEYxs+szneC9MabQzd89Umh4skBzGOb7Y+OKHL/4ibOoui3NX13kYQTJvKYO1GjqOdWpZKWvkws5A7TNFjnXaKbWxA1tC1pi+5JlfaAVjoWw9WgVqcXnyTOW3VK6sNd39f/mDb6JaOQQNEl9iRc86a7y6p98VU8djulhYcScH6RMFY/P4lMZYV01SHJ+tGKHqxZcOWGbp1S0wZEBQIWHdwR5tU+RUtEELZg3/yXbwJlBFTwIb+QouMRZVl5usr61gVaFttCPHseh/kw4jj7LTPa8F7EEwINSO5s3CnCm3R+vXh5kWJ3cM0ACGwC8qHoFWS2D99UFZKNvtqn4vdwfBvHTr0FX4D6nsDlMnqx30VZzOrBlau5Srq/hReMBLLTN+E7wynxEYz8WqKBgUrTfBFGMj3O7gBtwNFuAdcz7cN7xBWl4rZY2liudS6KYvw88w3QD4/En1ELRVsNZJhi0746qW+V2scoqiqlRNrcLu4e9dtrkiCNDBSuqcAo4XHDa1g0MmI7YzsKQtcYZpM6xmwD
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-revalidate-secret
      namespace: ${NAMESPACE}
