apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
  name: ${BUILD_REPOSITORY_NAME}-config-strapi-secret
  namespace: "${NAMESPACE}"
spec:
  encryptedData:
    ADMIN_JWT_SECRET: AgCLL850JDI0C1b31DgM1j6aYbYQoP3fOHVkSLXGQ/mxnTw9EyPkQfOfNlfsI4qonqyNiUCINQfSc/LBs/jRMW0Tf64s61xQO56eBkwRIuxmrj5iXyuTDrXZyZxpHZnfWkS3dxX715PJru3+224AphjQlZSmUmT3poCL/ciTKWespMvbLaBeOo37v8EwEWUMoXjw1DLeBjkub5RkqZmS9WUZUWLhWxDRmKicAI2qeCItg9VZUCakICw0FeQzszIdF+ZL9VKJEqAt6XTEBxAsMV996az02CbvjTkouUpTsaJ/HhKHK1akBYtDoTA+nq8UZNsOA0mh0n9c5EK4FuwYyA85pI9a9MIeinKpdwUTiDcAuFQnI3m0bnf/DbrcRSGiuwo8C4FcX31MlKBL8c2LHMgnhPFRzdTgzdsSzBFW2/Rm+hSsvHt5/Cdbad3S4vSoLSW9QgxdcCbl3MQF/UFlCzuUuswlMCilH6rSdhyngk4t7NmBjxTrpwnQ3k9dIcCkNRfIf5ERbj0iBaimsKa+Ji13+9Tpfw6Va9rwcUgDbv+A7bQvxAqs/2UsR7GzjtbHi6HhkHrKFrQI4HXL7A+zGQofQhNxKFvwfQ5608/yfmTy6QGTtA5yS1Ui161U8goQTdWJAiO+7S+rbXGvwmMK0tSUeW+H6E4BkGk+/xFKaFgLNhCoq4JqgFX5YxC3dfjlCQXVQtXnKIEYLEEyIZRMEZ9n5I0CL2nOdvcjerXv
    API_TOKEN_SALT: AgCHf34Uvj/7a2YtmQP1/qu9OEXCy8H9Y0BCDcUyjQN3uics82bh13h8H8iTQf3OAlbgpGN/5136VPIyt9xLtmWa0t/fdJjTwfF2hpyMJmmLKZbz8fQB14CoQ/gfLjiKH/DN8zdm8QV/AnDrSlBtRU5aqbqYxTZUFcP/omWje6eRyPlHR0+mSvsp3Mu7pg11pRnM8ifD0WrMunkd5f8o0t4c0IUma7eE08iC00E3gdsKid24OpT+QR8M+oZNbaePw1fa0/PhkeCfkdXnkvEuNxEMPLGM2HmHsEtSXDLy97PmPORf6UuzAoMCbvfSB4QocySQrSNiCu9U3PzbSSUg6GvBsrS6P6BMlfffD4XIdaBI8siA7zAj2QSxUG54V6LU/xr5Or7cT1HFhhDh05oarZfRWrBZYX521lGOfP5hh4bHZRL8+JrkBy7DUmveAxx/j4n8frq5nadmxc9bE2a8rchdIKLSdzQaQyfh2gSeAEPEorlGoacPtC/5bPCVyrfazqjj71dczEGStnIGLUHc47kzs2mSHF99EUV4C8dgl9VbQ0mxsWX9Tsa84dDoZpem5wiMcmkW9nP7o66GYQnZyUmH3e6d8ppu7pRWWlNtCGAzcJTRR5OL8u+gNKeicE9VG2oeszzdwkmgbffIuGlm5z5H4GI0iBQw5dA5qSGhfbAxbO7qnWzCLh3oYO/ybACGLyUpii+TOaf84G48OlVc7wLOwGoliFktJUvIME6/iQ==
    JWT_SECRET: AgACb3o+UuOQpPhny0/j/pMvqJ9+P0eviDU6+TcWZlHC/oQD5kaJLboY6UX3pcWeB0rJpp0HuczdVppUFbn1TJojnb6xne0R69A9g7lVkL8O+aXoWhhTEzSYDFxl5FBdK9q9dXvQXyFNnbOJsWPOnWOYBzZq4sXKuSkDWjJam/SgpkHxHiDZw67FxhDizmAa9hVishoOz967UUKwdqIoYGx8hCEDQy2KH80lZuajoBZuMJOs2zKjzOTUa0pXtqYRdqVAJt0PIuEqI5eA22hvRA1qGI2jB4/EiF0jt43y9DHcTCCUatGiUa+4fvhrsyACusFYfPVtA2cHBUl3EBYBL/OpkbCMCWATN31WfWGIjU5udm6TZaPma2Lx52XXXuQDtSfyJaVJ48vwytcnkoEx6qTLr8yx/s++VmG30N9Ro980HrOv6JiuSmE6Xom7U4G/NbwFAQj/w91OGosUJLJ93bVLI0J+fYQ+826vdVFHvxzaCygpIvNy49LvyB/cTk2dnhQfczMUJL5NH++y9lSp30QM6kpr/HqoDXj4CmWM03xWxqDthYmAHq77Zjg67WJteEFpRhPtKmij2k0IxB2V/K5ILMLZMXGJr5Yj/yjxV2mP1J7d7hk6FwhmgX+9ZajtvVjidJnXxKtbziYMhu/ZJDleodvaJLGngvqVSmSRP5p5lEc0c8rmsfi0Y2vkNhNazthRybX7diEJJ7oV0u4V1fMoq6OGvxfgZy5qgns=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-config-strapi-secret
      namespace: "${NAMESPACE}"
