apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
  name: ${BUILD_REPOSITORY_NAME}-database-secret
  namespace: "${NAMESPACE}"
spec:
  encryptedData:
    DATABASE_PASSWORD: AgBRX0cu/GYF+q08rs7wyrMXNdMelH8EgNfQ2IKb8YudLJxmzH0kk6QSU3xctuCCJXe59JUwhFzmgicgpLZrn61PbdsoKyC28eO2aKWw3wiBxkjfTkOSIfstqj8QPEG9ecte1txKV0iYFN+Xuj/U2tRn06r/w/h9CBGQgZpRAgYinhIL8XM5aXC1xoiTf/U2p9pjmQtf4SZPrPY0UrNOqcdU70QsfyzttTd5tvYEzp/MO59sxaw7MWA7GGjxMXdneerDaNoezr5N8ZiUmnSHXFsc2QnVU3yiRf54UN+8TUX3pXLV95hl2oyzKwuIXw6sXtNq5UwDusn+8TUWknETQirgu4ppBefhy6qjlDgcw6nMi36U4BtiujkW+5n4OMLGCB1yfeqa4YtQo5eqx56gK2kTR7Kxc/+O2XzahYutt9MdA4pPt1r1UEQa9as1hLLi0BDz3uVtGK0Q64D8w26HC2rTigohqybv3oDIBLsb3C6XuAOP65VVyLizbimrRPhnxlodjdD1hQ/zPluhHX/5kuDKg+l/xK7N2YIt2hSbjCSbKBfroQxRWfEAEoEPcFQ1rYkWrXGvYIkS6nPVxYp9SayzFhxrMKOoATNiItGJtnUzrCXP09qVBHMFasiVnk265lQdGuE0hyIslWBLxym3puB7aNdCQLGj4azub+T7enKs7SmxsX01mmKj5fS0nlaHc+3z2i7gpLNaPvkMll2Gea2/G4YzdCzzK5Z7FPCzolKkTPN7hs9wN7Zwyy+6T8IQStBYo2NIpToBQ7EP
    POSTGRES_PASSWORD: AgCYOkYUQ6yLqd4oaRW8jWGZio8IbNHLGPPaA4UYZCRvlEXk7HfDz+2GA1k29bb6/00BJeVNW9wm99jWaZu5Ok6WPUsjGY6Ybps4dKyrks51USqVeGqSvqBhO8gt5TwOWYnFD8lVHyivYg6eMTAXs2ruDX0ODdEnVeqJiXzBUxHkwch49Ykv4zWF4dIRvsEW30/oNjdLbadgIFzYpkCmZO2U05YRXftnbKTYr5MpAK1QKfCwzM0xQY84zcd/hY0LVKhKPpP1iwdNPNRnJKbrhKIf4yn0rgv9vPXs9mm3itXNuL8jk/9dHdj/3YM8QTjOYdpqEtKmfSl1mcsi90uA4hvd483X95QNOhPGtNwDNz5cNfcEZUCgZHPh/2LnnofjzrZ69j8nCo4YQC+EnPdXyY/90j6km24hKihY2FBa5AjcZHMY1Ts4mgi3TgASomAHUA9vIA+XzRVPgd7aSGs8WNa1/oynEz4fecNB/2/4+VzpBWCxyyDqGIVWVf4a12qbM6oewuqWcLIWAZABlj2/I46o/VKLFYCFDoz1mxeStklNjyu14oaTQG9oGrYKEVUVmOCVGwTb77LoPJblENIl07LOYdJkluzbYq0YXYaRWj8iYgx+kLZn0QuNR76fFhmA4/cDjtzOS6E+3V6ct5dV4CB5dG5fcC52IYlOT3W9J5Q3yrcvr0HL4lBjLKmCnfm1nvGGtdc5TemBH/z6PptwKZ4/C15qspr7O4N6xA5UnIgsfCxtXr6SZYeh117B2dT64R3YaBdpbYBuzsZQ
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-database-secret
      namespace: "${NAMESPACE}"
