apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
  name: ${BUILD_REPOSITORY_NAME}-mailgun-secret
  namespace: "${NAMESPACE}"
spec:
  encryptedData:
    MAILGUN_API_KEY: AgAEP49cNJy0hgdo8x+e11YmcP+U6agqRYeuOWxbj3R1J0c6J3i1m0KCZhSc/0rtYLkeJxSbl4Q1KyI1PxmKFn9vqcPbcrIt6iYUmJqLLoh+Ej4tRnCYBSG5XT9PLUd6oVXSSrPki4nZM+j9eCPYsbDSXPR/HqzFk1CTSVHzllyDCCMIXJgJm3IGrh4qgOZaevItjSjowfP7uTfaVVvAeo8oMny7FR2roov5DSNQX69uZPpt0rx1KeHoG45jpzwNltAKb5mzhgu7kvm8MgSH2HGpZLZCSq0jrFOmtJc6WJj6YAz2sv5kx3hFB/UwGcXEnhgBLAiNk9IKO0UW8ON9qRRKaoLc9vDcLuDUTu6PNaufPUQz/87+DFd2bC74eiM3buv2U2E7Cl5kCBUNi4WzUpcVLch+q83cEwI1PhEBCeMhVrsoAVqQrBWnU4T6NsU8kPZmtSXPB8KF0tQVL69ckpzmW0dQZJPG864lVWh2XlMqetY3w+YQHNWUHB7/JKzOl3rerahTVoNvR9Woiw7ecKv3msvrfchGsgYrBsVpqYDUd/H3sl3aUzzpHyg3iubqP7OME2+h39om0sgbw932Jl57HfYsL+ZOd0fu28pHktkuhI/BUA+jFCUOkeOttjnBI2ek3bexglHmNUef7vOEu/KOTJMDAICVizOse5nS9L9OLxDJ2I8j+l3u/Vow/tWniHlXOCE/r+dbSAo/2VdzzmHFYjksnvZoV1A6uuLr5ocRuQAeF5+Raw3qp//M38LqchjUvA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-mailgun-secret
      namespace: "${NAMESPACE}"
