apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
  name: ${BUILD_REPOSITORY_NAME}-mailgun-secret
  namespace: "${NAMESPACE}"
spec:
  encryptedData:
    MAILGUN_API_KEY: AgB3KNIGtAbX+/N9qajyUdctEIXjG9jbhlyOBzp4pHRSkspH1rR1+jIpnkdM9uf5Y4l0WNyBgH3sSBslyUe4hlcut37fD8JGnrN18B2fRfaQcO00wBx71aHUrpjo5FogatMHcM9lI4Wd4PNiqLRz+3eaqgWGtY0DvRFQLlAShuaj7TSUusNZ8e7fXyoj0mZYnANm6vh66WFKKU80MDME0DlsSKzZxQ/trbPtHnxrJG756OtDCgh1YpM08yY8ejqJMhxtL/UVAITB7Pf8WcoSncZ3RWe1qLLcp+UtpBZegra9aUB5d4DrpanlMmdeJI/3LHTsGYO0N2uSKESbi7v+n12hfu66UH3M/B1kD75vs7eDc0aF3xIH4b4I7LXkurJaACD2Ir6zCnd7L3/hIWY5NwqrOD4JFle+7AhTTUlHWZuyWZxKMjv7qqG26StsK0ppd5U+M4c2lmZqODMwJHO8qmblN0G9bY0LrU5GZIhx5g/8NNAiDo6QPmw9cyZWfFzqlEcL5t5I6UysW9VlQcazQ1yyG680HhsTQ7d4p2/pLWJDCp3A3Y1s0bWd9uZQEm2g6jXitteHCaZI58EychauYY5BcQ1NhhRwSm86NxSFdN/0C4Oe3wJ2JpJ+UmjfbKj22Rvz/+PzW0GqSOHodOJzK0nRg8F/X/M73LFgNIthZELDalrFFTlHOmAQjeEfvD/iwQ1m6d78Op01pWbLhlFnX/fGU+x1GeI6p1BY/NOl1O/clmjy0WH9JQ6BCrsCTosiju/dBA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-mailgun-secret
      namespace: "${NAMESPACE}"
