apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: ${BUILD_REPOSITORY_NAME}-minio-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
spec:
  encryptedData:
    MINIO_ACCESS_KEY: AgC4if0ssMAEHx7eIMecUY7h51XCNzdThQBPWNJ+V7EtZt6L6bgkouPgNaY4gqAL2YtuOqPQFBZjRt+a5UHvEmU6Knbi7wzSC/nODB4/WgME0E2vHO6lt80bDOwV24BRQQfA62Xp+QH9o6iuCxVhos+ZkhHy3zTred3muop+ht93/Vj1/YA/G/oGM3bY/9d5TqGh6UCsNGQUF+UGFvzRO1ZFNPGsRvwlG8REve0Vl6xVahv+WFHMKMB64FZl1FNm7TaC9KWVsUnjCRoFpArl31QfcNAx9fY6tC1lptkDg6sGKTmCEhHJp8CtCP7S/ux0Ff9Rlhuic/r4Qo5PNQqL6U9UoEnUzKIL6n6Mkav65xQAj0LCKb/VoerCY6vaQJg+DTPGECHHMCWL5i7Ku2bAU3TAF/0a3U/g2Vo3Gv+O9+gfowvsATruPVisLruwlIllFnrrhf0BWEo2UCgBjHAG0LnBl6DQBrdLne0df901XtXDJ2Qo0QmPI0f+YyaxZCDAYAasmgP7JEbdnzM4pXJIW2/8BU3s0PiawTvOY3kqVMuVVBnpwSyuGF0s/9fqzGBnDXf5KVo20otj8plaHYHs9hne4y/kM0pHQJQJGPZhG20WaYZ3NOweDPOKAv556j48pJgxerEvQzaTqN4blhwpNfr833B+VJ7+PEZ4p5KTj17BZSHpQ9wiOcX0Di7OddmrKr/bbJQ=
    MINIO_SECRET_KEY: AgCvl13Rx6gGjq9OnGbyTcuzwdSx/aEvkOTjvDUpCRGAen2PFCBZSPncMOYfobA8nA9iTbDHWjqACP6wjMrYiDkLehC3eVL7SIQQL/J/xyFMZHA0y4fOc7U2VB+PUsScb2pvAfrlkv8XxAj0uZ+372F/q8ctlWVUDGczzgp2aUMBV7nH42mm78/2ULPOlreSEoTLfVWU3Vy0Hoy4k23ZJlNLkCQ3tOAnzzmK5Mdhtd3q0dZbWrSS/6zxq4BNbDgzyphzeVxPZIWw1K+Oqmd30tygsuP3Wl2lEOZ4d2I7dK8cSHLtBiETFy1oclWhd+67A12JGj3E7tcDXYiREqGNmzE9QLSB09fJCa4OtOOF2Dw9py+KEy1+RRfvHIcCVeUHfj1ahlPOCaFzyb+hINYAxPYO4J9sZ7XwCLVUGVwwb9Nm/HLo4Ap2Mi4Iay37pwTKWlDr0sKEATizCPi8RtNLFb8y1CZgGt2Fr+ptSv+bqkvK0uJeQ9mr3vsdwVG7ElBolirQmbExTUQ7V1roE3vBafqv42Dd8PEbRUZggYJocICGAQmTj2cLQrl6KPFQ3FCHcgYlUr+0K+ez5YQ6AsXVGEukVDyXDzQk9oi7KuAJS4wpncvNMgJit683Arr7hjUzly08JiL08vXom1TEQcZlZY5XRUihkGK5c2hdDSkTkVKZbq74x8FOCvA+B01sjfwsgNBca5k9bNbISnq9hNrdnUS6B8xk/8kaCUEiW4mEkx0g5kfS52cfKZ1YMSnvG+6ZSO8s48JzpvVOjA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-minio-secret
      namespace: ${NAMESPACE}
