apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: ${BUILD_REPOSITORY_NAME}-revalidate-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
spec:
  encryptedData:
    REVALIDATE_SECRET_TOKEN: AgAsmT/gKqma+cbsxxrmZbFGAXN1FwSBcD4p5FtRn9uS6+VzEZp15cK8JT8d1vNoUV9Usqq6+CrJe04ZWYvoOpdIfcYeBud/e7qRo3gvimBEA0hjTKcLsA2+zjtOQE926z0BmzLGpvm9/sxQU4EtGKy9n7o6jn4AytSm3Pk8FVArC7yN2+JD0G2wso70eDd7fpaJ9BEsRRkRxhzN6qz7KO6FjogVWmCp6asPYiA6jc/cRduIQe+C0yuNsZL8QpAJx3qcXiRaESSddVz4XFNY9nn7BpGVDXAOxHYt8PxLKLi9TaLskRR4T0jxPUW6xjaKj8gQUkiQZqBHIXLdx/sn01Q/5QvHHCDlPOgRVlMV31GoGayUoVb+HzzCxiqzZT8+7ByTLMnwLLKw63mTKSKJIykGP/GiBd4OuMQmc7s3yFjpkI7fjy57M8Sjr0WO5uUSlSnA+i2r7As9zhxyEM/efHBj40sM0tOVW37b45lj99Go+CZTrpCuxhc/NZZsGsU39Uix3Iec8znoIXmiEqX56CixvIiuOPBrCwPvuxEG9qT6AxLmvKhF61QQVGoSVKHU2Ab7t2ip+rm7+UynEEZssd9CALHi9OXwgL+9rJHOp9cFA6W+GAxOlY28h/DKZXYN/kUargxBOfzsQ7ulLMFuFvUofDr7JKx53UsDfZbXpU/v8Gi7SwKMA3vhq+MawNbPXpb+f2WNLNlnjrulrOWennvSNc6yzu/tQVaRH148bL5aVw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-revalidate-secret
      namespace: ${NAMESPACE}
