apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  creationTimestamp: null
  name: city-library-next-cloudflare-turnstile-secret
  namespace: standalone
spec:
  encryptedData:
    CLOUDFLARE_TURNSTILE_SECRET_KEY: AgA2DDI4ax+i4uuInCxVOa4B7bKJKra8wleLmfJfk77kZbUTLicYLmLyEoE3xyHzKLlRfBIXLWO5+uTzu55fURPO2rg/IAkFCZ7D7tBMfx8Uno5DmU1eWaYcon45zkAxN2Nxf1+mtkIS2e2C8WgfiKUlC+4KPcLi2WoCr5lEUsvqA9/l94e3iEO1idYPML90LKreIfaBGbd9cvay74jJCtbz3pYZECLx7k5PXjL0402k9yPxsHj8be87Qdfk0z0Dpp6A3N8ox7aAhNhMcZYhH58lN3z6qMFIrxAeVlTVK2q17cZdqNzxSmYyKp/nMbV+T+LikO4N4TI+YqfTpvRSlmDILcTrNPplwQYUd3lidChv937rOoiNNFz7b5j1xgSctaHJFJKb+Lt+YBQJ3n9KrIwYWnV3GxQk6r4lOBgcv5gKUDmBJt7FMiSf/HTu5Ab64oOTTq+5syb5SQ7/i3FuE4U5VsXZaS7b0pURkC5fXhDBAtXNmeMx9AyYnPVd47JhGsVtl6z3Lx9DoOnESwxt7oui1efClMf91V8kCJyBGRtJ4hfDPX5VNTJbk52Gjf/y1G0Y3x1/nn941Y9oJBmgBlWt4FPn5477MdSfSin23N0nKz1qk4zbOqG1u0++rzXM/rg9kJcvfW0mtC+yFUhD0su40s99GWpKzW0PG5hw6/mIpPoNMcD+GxKUoLWT1QRh6oD4Y0QxjG6UMmjmr6kMD7O1dy2s85axWltA4Or+mJfCvi1hkw==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      creationTimestamp: null
      name: city-library-next-cloudflare-turnstile-secret
      namespace: standalone
