apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  creationTimestamp: null
  name: city-library-next-cloudflare-turnstile-secret
  namespace: standalone
spec:
  encryptedData:
    CLOUDFLARE_TURNSTILE_SECRET_KEY: AgAcMqflOd/pDrJm51+yeK3vFDMg+SVNUtk+T2BG727N1s12cudAdc788jOXtSSAc8h8CT4r0asUpjin9k6sS2f1dJGwH6p/lhRVIP2+orsYITzHFK1sn8WzyjN1fODWfcvWgPnJP7bPnK/CZ7CkMx7KlOrp/A51SBUce9lLiIRITQM00k5ZhpueERy04pSuZo4ilC5dQS9jyCjF3CvWzOb23O5bwZ0/Uk0Bw/coW66TtLhr0kT//4OhNvYGgEqlgd1AUFmC9Mw9O7z4qyezgjuQJViNebNgSy264txsJOv1Q18/eKqdA+vsD4Y5hl41pKokg3w9m0XqbDunl0OrIn3wF8dw34YBgNi7BXnOKPMVgxoCnGQfcLPrhyEBWk1SekrkcfHrof5TmnSsvLQId91xElOD/+lJH5yVsMwBYBMjOdy47jnf7y7CQCAsckoEJkDtFI2ieIxchFm6sWOTxy2UXF1ZdgmE8OjTNIhyXviLSSln7f1wL6u/lp4jvTfu5UHncLdoha1aKtt8rBxWH+OTzSZD6OwFE8A0Ff/mseYdn3mFao8kGNXcx22N8Skkc4B88pOTul7Ag1dKgSOwidhpKIgptdauNTV3WdOyE1PgZ5JOA5f+y3jyI0u02hYyWWfgbp67braOfRx4ElFWtglXPm6g19uvi5zJ+vn1eP/UNK9wuUvz2UboYjrnCgsUqXEHxtwMyyr3+/63BagNnlmv3KbWfKLGfr+1o6i/P4de4Xj7KA==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      creationTimestamp: null
      name: city-library-next-cloudflare-turnstile-secret
      namespace: standalone
