apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
  name: ${BUILD_REPOSITORY_NAME}-config-strapi-secret
  namespace: "${NAMESPACE}"
spec:
  encryptedData:
    ADMIN_JWT_SECRET: AgApBgTiCjmKHbaPrzYVcWQDDxrY7QIcq/4TpHKsPflcaPDFwxEk21VYAXnstqsV8W99udkftQjoDjaejkPCdLMqieks4mptVlSlNZ0ahz/jIbJQ7dYnE06jbdgW4V0oNbKy97ARYr3/cPM38JSTsq0hYdcSVxFyubtF56bATUR6W2rYMkDsj3ePHcdX8yJn9kiy7xsguZe02VADW2S9md2X/ihNO4k5vtTdOBxF9q6AvUP/rwf+TkGR/0TVnpFAHrMBgCp3Bpgkcgw+MqvsRfjpqJus4T+fmuUZOHHCOBCbdiFzIE6qWBSkoh0rkY8vIdhb4LPvKAbCrDa2ZHUHOHR6H5WR2Ofj/koaEPV1MQLz0pV0srXa9e/giuPPDRr16C9YUQLXKroFvGev7nqiNQZZ0+d2qF7IPbHp9tKWI/nEp+toeeK00a6JIQ1ozhOZVBjr1alju8D1KdJTfWpMCx6R8ZTx/iXX9QGSgpP2qZkh7s8KzmMmq3hbN/qHI/d6WntrdfUUmoysFMSVz2B46y987oLWKNBGpRyUHu33scCCSjbFcG/SQtAEl9xyfrAfm+qgw50vjNlPAMRWeb1d/i+MhGnmXvr4v4ytmEjR9aB4IAGoAOpIeKv4SsJ54i7IzqeYG8JkO/cGKIxDaX6EbvMQg9HaVm37LCLCe0NdZ0GlKQ3J7htA5yp+9Rfeouc6LhWgIlLUkrWvRt9MtbIKNDkRInpAK1zKdbCIJhRW
    API_TOKEN_SALT: AgCEP5WVUD83Y/oMTTQzHfY2LGcQcr9vm9l+KAkuIYirBe7xjugYhH7tpJtS2bF+GVrb4tHptS+Ft456jOrhsEUVKYj++R/JfviHdmZXwa+KEpqLwCdlNeAb0qjR/v9Ef4TPPvR3RkD4AyqxNIvLik6S+Mihh3keGfttyKY0VHzYEWnzIqeABiitaw739rCZv3TVFD3J3jAzT4FEJMAFz+WPFGy8xzMO6x5pctLrBDWwmlL8EcHj3tTfaGAu5/O+t0VCUw6b9MtJ7/4MoMT/HHDHkwgwM1ZlVlsKf6Frzq9zXXLKskvo64PzD/7tabc+O1TbNFYV52uj0ih4vBoF2iG2FdGVGMrP2wIozxyoS684JssftRnHQPA0H5PT1HdYL6SfoSGkIYPHhCPGiYr85v6XuYKAN8omMb1ZI8wTQki64lgi5BPIEeyFOHXtZ1tEhLvM1jYaR10vaW9SOAknEQOPwu2iUc+cxP0cbinHV61m0SNHb2WEr8NEQmfAn1G9Ln10mDECCjCn7L06XpqQhQVqOdscVqwdJ9adDMkKN0Lgxn7QEX0TN6Mwfyhq8XdcCtLrRUPQ6dFqjFlZrhVciIVZO7DOWL1lpF4iMGkQCfDlHJUqLUmtyom706G9EQoiy1A5alLedjPhlOuH7P6P/jPmc7uS7vdG+0a5e9rnFwVuM4/+BCvW3ELczPVO+8Q5Jh4qqNVD1JapfqVgR1SaHnPlRcYJaGd+OlzCQ4wBiA==
    JWT_SECRET: AgBMdOYP2AUAlMk/qITbc56fWF8u+e+NcBLcw/H/iE+1vDxfuI5ghDxp9KUSc/Bxw0o9CBIlvklNXKxjG98ZE9rr29jzqsSq82zW0lhNfWjYwDGg3LnO1L5/qVDTz13MjhJVjixaVI+HAvPPdqtejYy+QmEspgOCoWQvCQzQ/SVeBLeYLpfY/aJwKeXN3RMCABXpG3CEVlVf0rYuTjk1TTetIqtDxRLBOHDp7oS3v+uNnOxmbH3xRZdVoeXgkyNmc+J1GT2m5I0eXBswsKsFmOI+vFlzrg6m4eHfSKRgzdAp1WD0W2vUR2adBdo9OS9S146e+oiSTQtfYNgB0E5K+y8x423Z2TpHNTGZpWoPwWoMHOJt8EuhIXz2NTR8NI+D4+4AOFLEOQeiYE8WFPeG/58W1IHBKCN5CmV+nEqM93WJfudtM1A0/p3ralpG2AlN3KUbJcTbMZikk86TTOHWP2P+6ESyf/DBfbykqH3cRx51yjB012RsZHuSQqFd32pCNOR6Dk0FSxS/Q6lbIyTvG5IMEunn8bWJpE/4cpIYemG4lRQmYpnX4eVnl5LdUcW9sHVBXCYgJuf1RHjhJ2fkC+bdrcm042Ociy1uUexViRdnXLc3Emfs9bBa0PmAVL4grjVsU0l0jB1k82Vldyv+4kz4467XdFGs7gBWE4psmmfony0TEiZeK+sJGBKQkE82PUHgsTWm6cUNG2sJYA4Zu2ZIGuwiOqm/1mYnPEg=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-config-strapi-secret
      namespace: "${NAMESPACE}"
