apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
  name: ${BUILD_REPOSITORY_NAME}-database-secret
  namespace: "${NAMESPACE}"
spec:
  encryptedData:
    DATABASE_PASSWORD: AgBdAQOsFc6fZkvILgPRcW12TNutNLFsV7LCGkrPbx/GohmE11iPwrQ7pqB/rxhFnDUSWGo9Aam9k6kWYDQvF3ThYdhlY3gglPKBk/JgTOzsy81kPzbwnHVmSkNrWBLyJNu6sOQWVITeBwbm0JkkWo3Ux8egU/NvnK82TfMzg9pyHelofKMjPuWF/4iTu4qgl203UlLEp8HLk6Ahx7qe8ncTELan2BElK6c+c/BFgfwVpjEjqVlurZ+S1Q3d0VnuO3vj7bDlsblvhzhp2fUtOOtd3kGcJOBmC16TaDWbm6/gCSeB7nGPebkJILjOV5mQcydwevicOc4byOTHP9rrx68jwcFfqmk3Q8HVefgRkv798eJwb5F0Dzgiy8UFXCif++xt5D6QXTrBkUNuyJmgYMGcpRcwddtyKyZbqRnsHub2VhGAPl61QSZQDwaZvhzUBHhsihBS1o8ij6sw4XRLaS2fZXfKbh7Gob57bdcLlqZj9/0RbOtPYKypp8VIDCTFLnTBBaE6LFiFRIgLYfhX0aVnh62uxroy6nEvRSSlRaljxd0Jtg9RAEOyGxFIrcZsyPgR7/6cHKUAQgqSO4n63HXK/m0ei8Lj/i9ww1Ottr+IkXIZS+6P2sXR9kc1P+XJEKLpn9QRhxnp9n81UJg1rw8yN9zwr2YcvG58v/MIBrQDkdFvQSYHvnWcFp/OHgn4F1hh8X71ZGAh8wtbtzb0DdTIbxpN2FA8qLbnqcNJfMdmLaHTVNU/h+pwtn7R5LDkZyzJIw==
    POSTGRES_PASSWORD: AgAegqCgjTTQXbWtwbCOHEEbAos2kF8H3W+jXIZvmEwC2W+qgr+sCWNFRVYipnv22Ho6MIlmypb8Yma1UHEeiJmV80B1jRMxKalg+19kedfOYpuS/cijiKVhQNuHksJ7JVxSFDYf4Fb8fwGc9YMhZz9Jn8eb7DseB6kPOa35w7GpeAaR1U8RbO3QYxh27P+m3jbX7YnHpfXM5dT9T6DEzgYvWgyKSeIUfpOnicXU5IUPwK/yv04MiHcUDaMP6daSPIWfhMvgA2d2Cqr8WgWoCI5a9lIXP1S+aFGHAQ/pQOX8RMV0votkIogd8zPI1sNDxLYLAMsO1RZLAaxC6gOf2z43Jdt1qfiW9lVwiD7psUYj+RaDOJdNNZ4A8N6v/aWqaKVI5qLTHJBuJbNb8yKe+2zTifXdtaZ8FZ6FUmvL7ethdL/meVokyJYPIhvjNctiYUPeB/IuqZFEAkalOVYZDn/svjhi+V7W4+11wOBxwmU+uFM9lV4Tkxr2KguQvk/o7z6AA/Fov6quRJJ0fDoLMLRpPBV1ShLuo1Y4i/n6K32E8Rqc35F1WQFgJo4yGaCv6l45rouMjZrTq0nsePQYRNFgFuWXK9LjeSeJURBk3CDr9yfCICoi0/dgFBT5pjEMXA8Wdqi4FaQZt2dpwgi7ecbOG7ln147zic9gkfK2RKS6s0Zz8BO7FbPp+gs0FmkGndCOeXBo0baot70eybUq08rFRTRK/vOgCHNJxO/yWvtjthOTh37hpL/pWV3sllx4lI7YRA==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-database-secret
      namespace: "${NAMESPACE}"
