apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
  name: ${BUILD_REPOSITORY_NAME}-meilisearch-secret
  namespace: "${NAMESPACE}"
spec:
  encryptedData:
    MEILI_MASTER_KEY: AgByg8SSQBTVmKmPH6MSkBUGFOxR52hAcOAHf3IDwXcIS4BDsrVdSq3qygZZRJoFCHSLdlVcQASDRqMXCv6Q9GIvLznvqdRG5UBS7Wczuxzo1ig15z9f/e+PrFpEQtYeDKu5TTWmqdWMtxId78BhDcIPmGAvMH3UYuzgrJy2II//WMiVL7JdSUdWyFRl0yskeePk23pXfOn9tYeX1XzH+3/z8RoDVcjwnhYW6ff/O92Tk2TTVzjY+RLZHqQoD6R8Xb+5Nz+wst0aIjXD33ufz/cJ5x6fx9M5xbmMBEQs+u9pAvZtONfATs2J83YX5qZlzCkTOhCMMCnFFt4T6wTXBVJlkvAkFCqzYgV31lw/bWyr0qt4dO6cRkUOXnJefMr9YN2mDQ6KxMW/R9gq7NtMJWXMJstFdavDuOqx2SPZc6zRR+N3l5jgKGBhzqlU6XHJzSM5raRs3rQAF+PY3lo/Bx10o/cF34aq9QO9VNYp0BO5WnwEJmsxMJVpGsE1A7Si5YJP9vulwJtwBRxoPvP8lhlsFhleJkj7iZPg8Mk7c47zDUjbJSjxFPwyL2gjnGx0vuQRzA3P9rAzV/nHam8P3i+pPNZN1VlZVExomFwObk282m7D4+AiD3I+6vvfhpiyXnTRIqk5WkmP1XbvrsY7A9nfnBzwZJTlJyj2/7ioBMAZ0OBJ95lSQccERZ2TFgkcUn6AzcGXOd+xU9tRgxwUAA7dldT7W3rF9rRCDZPbX5t+L/DXrTYh3cvn
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-meilisearch-secret
      namespace: "${NAMESPACE}"
