apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: ${BUILD_REPOSITORY_NAME}-minio-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
spec:
  encryptedData:
    MINIO_ACCESS_KEY: AgCZERSdclvoFT8XaR1xaz3XtVeouDhqR+0cAfsNnWKJdijUJ4vb7+sQpGI+WETFOnXrwG1YoS25qJ3WXg3572QAIJTKrqEvHZ9ulsM8YkqC1GBEZj50khKFr4rbZWYDiUTsvI/cDosD4+83A6TRYUaG1pqGbWiUQYNxwHgP309END7n3FdSCXNZ6Vu186bFhVUGl0Va41CMOrQuC40q3NvUD3jUc8TElx6QO03iu1dR4AmQFi/NfIKb/yh2HR4OZBz0zQz3Mmvgd1CN7bTiaG6DKG4O1yvXzs9oplbc5oqrMtJGwhKTymOT4TbYVlzRvG2/YHMDGMFwnkMb2TFWIzOOPTVGbArQcz2zWT+9uXvX7R6e4pgLTPKvaRUs5J2mDNrfqDiD3BdzjgcZgAQNLnTxepXBDM0PxPDwR3ExRwKN8zGp7d/R5t/hM0FoznmnT49ulPJx47Gzrea64ELNYjR7QZH95QRMXoy0pRfWpVvFa9KqnT+u2QTfGh1t96ZYRBBSkxKuKqUBi0qYR2TPykzU5gVsR5VUL64zewiC3lZAbLlCDkUY/vKBxH6JTzaCJj0UJTd5xirw56Tq6sOb/bDbZ3XVva9c0KHXOdJJZizargLulJrjlZGRU8/pGReLa/Nol2b5ngj4FlWuJUz4890m2I+FCWlXo4ayGgs0FepQQT1ovD7z/PyQ1x43CUTA4aDU9hY=
    MINIO_SECRET_KEY: AgCtzZTwvjIQDnf3t/JRsfKUMSIiKkvelV9C91fdCLpDhLIv6LEyRTbbV8/+ZxIpX+pjyAtfYDi+KUNRK8AjZZKb6FR3dRY7JHBmEQrE2asLzkvd0+O3xwFkQCAu2yh8OdZ0bYttZ6tHLHp6o9yjWl9jaSl5I1odY1TSZSn92r7du2kvxRL4xLoA+uG1SXrFp0a1RczNvlU4SZnitiCf4hMTmga3g2TSKz0c6Jim97CctTvRMypaSF9pSsyhpBNt5EAiMIYXYUyKaPxpcUXQkwqHSEsV0GZBpalnU9+ZGlxVM7xpZYLT9jwAKevQcXChyKcA1dmaO/j/NOfOzkAhD5capqTxnyYeHFtAgQWtxM/by0vFLsVrW/03TG/bVHNxTV6ELRj5C0Tp2HNwCa8Sc6g58M53in/4vjKbfGMKetgBh/6VpukrHhHUsE4de+Zl5EDe8P6xtfkvIlqgCZzxgjrJQH/K+4pxHu3uGdiay6dvzogymlJQXqAMHyRC0kUGDfyl66wbp/TgQSFtAmnpk0XWgexKU9ihZ262ngQhtMrZg4lHw/P09rMm4A62YjfjZqztt3zQcVYi3p2aYB6+I5HHbiJlvyIckjQ1LxRC7K1FdC4hEfIDmlNWPd7KcY+MEpzjbQW8nn3xk65XdtpaQ4NARPiBhaAWzH3HYGYs1NWdhrxH1ZvRW2DbkzIexQwRJwLLPKspVrj1Cy/4jruvaa3j5MENS+fRfBri1x0wWksy6zgO7ny0LJbgAlsZ7yJVKUUeWOU/Zvzetw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-minio-secret
      namespace: ${NAMESPACE}
