apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: ${BUILD_REPOSITORY_NAME}-revalidate-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
spec:
  encryptedData:
    REVALIDATE_SECRET_TOKEN: AgAATSPdIvHo022BeVhOuBPfWc0zDmgCobN58BmnmAuUF91Gv+RTGJz+/vUDQ/6e8Dg1oqwvfXlItbhl3GDlwM5ZjTFk89U6WXE+mWudV6Y0dEMc8XJ0b1tZNqpRcY+sLSvDJPAxjzMSqaBsCOFQQqLHUysdVpg2kKuOWuhgzL2t1dTz1yjH+YY/CxVqTWYnaxOXI5/REa4T5sLOKPvWW8zcRsbSvSt4p38qAZGYTi74hEIYyuBjlVjidzRX2wx3wMUAZlUnOu5VjAVknDVqezbkSzU8+2vk4oakVJL3AJ4uzJ1caelbjGDDDSy/DAnubB1aER/IvPh4dKiv2JMniVzULCQC4FjuDDEsyNWWtUuLtSxSUwWgTiDZC4JuwlKjg6Vb1EKJYzdlUcbaihOiJ2TZUhbdt/Op7riVCHylXeYcjru6I6bXJGfMAWIY5B8fczCOiax2DBWMkoBtTB1CurofHBGjLJkHabFu0m2KleA3OJJPL7gqQqS311mKHwLl0F03p4wNlYzXIUUIo9DOvUWEIAlfln5Q1x5Az1tAJRB0S/Y6oV1E9HPwwtb6LSJzCRyHuqFygMJiGhW/fvrw/niOoRAXnaPfUeFz0CP1tC2FrlXD6Zw6RRqoWiDfz/Y+lpVdeKAxmkCUsaNChCuuO8SyXoyb5v8Md2FS8bfCnn7nGwL135LSBtuVqC4icTxU++hM9IkZtwVg6uA0IueDX9jgV8VmFl9K+GkcMGEsD/W1OQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-revalidate-secret
      namespace: ${NAMESPACE}
