apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: ${BUILD_REPOSITORY_NAME}-revalidate-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
spec:
  encryptedData:
    REVALIDATE_SECRET_TOKEN: AgCI4u2VmnIT3OmXbFqZzYomTTZvl/MOC0Es+lGgQ5k4AU+/TD6/GzEL/UkjLSFS9pKpU7aHJix4ZQmBbd2Qr49osAxuNRRcodfV/5uH7isYQHjbg8+gdqoX6Z11zOH8SHR7NNnXUPUFNwnylPm4pJISnbvNoewNTnoBtkhvf1C0ZII2qcm+Tx6XYtsoga14ZVNf9Thc4JuYfX8zuB/WW5TgzJX74c/tXA8bwMqt72Y3CXsFHghk/oXprC2QJag9aS4z+hNYKUQG+0qSnNtvd5X2lYUMCI0n2QxpeVUR9gm88bDSe6BgaqT51BX/mDeSPfeHg9fMGnfkuBJftDkW5V7JXbmCgGfc16Yft1sv32L2wdt/I4ReFrfVdi0iWup3okpr0ija8dlidDs0OprFQICGeWQmJ+vKi6Zv4dXlyzhWmZgQi/lhF+5qbiVd9HsgJuoBqeyWiNOKsL2Mz0PqiA7Uz1LeL97l54ByQJB+NrJWY9JA6T/ZtDTPmS6bX6cOSdxbJZ9pRQRSkGC9aauKTJNsZ1EUFgm7dxNOqa5uw+kkuB7+ZUJaLD04o2PN1qJ3tdmAIY51v8dYiL4MgJfmYvg+fe1PGYR/uPexAvmaZrqYHyNu9PUA82sT84dvNOW1Sb6fGgObecyQ0JWozn4QELihUHbAVW/tLOI7iXVXBAtf5EgP5v2NhRVgSo7TXlNWqDtBOQ92H1GL6Acy+LnSj3C2
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-revalidate-secret
      namespace: ${NAMESPACE}
